// The rules file `Muse Spark: Create AGENTS.md` writes when the Muse Code CLI
// cannot run `muse init` for us (no CLI on the Model API backend, or VS
// Code's Restricted Mode). The layout is the CLI's own scaffold (Muse Code
// 1.3.0, `muse init --dry-run`, 2026-09-22): the same heading, the same
// first line, the same three sections, so the file reads the same whichever
// path wrote it. The CLI detects commands and directories; this template
// does not, and says so instead of claiming a detection it did not do.

const TITLE = '# AGENTS.md'
const HEADER = 'Muse Code reads this file as project rules when it runs in this directory.'
const PROJECT_HEADING = '## Project'
const ORIGIN = 'Generated by Muse Spark Code (`muse init` writes the same layout).'
const COMMANDS_HEADING = '## Common Commands'
const COMMANDS_HINT = 'List the build, test and lint commands here.'
const LAYOUT_HEADING = '## Project Layout'
const LAYOUT_HINT = 'Describe the source, test and docs directories here.'
const BLANK = ''

export function rulesFileTemplate(projectName: string): string {
  return [
    TITLE,
    BLANK,
    HEADER,
    BLANK,
    PROJECT_HEADING,
    BLANK,
    `- Name: ${projectName}`,
    `- ${ORIGIN}`,
    BLANK,
    COMMANDS_HEADING,
    BLANK,
    `- ${COMMANDS_HINT}`,
    BLANK,
    LAYOUT_HEADING,
    BLANK,
    `- ${LAYOUT_HINT}`,
    BLANK,
  ].join('\n')
}
