import {
  runnersSliceSchema,
  trafficSliceSchema,
  type TrafficSlice,
} from '../../../src/shared/modelsPanel'

export function trafficFixture(): TrafficSlice {
  const task = {
    workspaceId: 'workspace',
    parentSessionId: 'session',
    roleId: 'engineering',
    held: false,
    createdAt: 1000,
    priority: 'normal',
    size: 'M',
    overlap: 'serialize',
    currentAttempt: 0,
    attempts: [],
    reassignments: 0,
    reviewRounds: 0,
  }
  return trafficSliceSchema.parse({
    board: {
      workspaceId: 'workspace',
      windowInstanceId: 'window',
      paused: true,
      tasks: [
        { ...task, id: 'ready-one', state: 'ready', readyAt: 2000 },
        { ...task, id: 'ready-two', state: 'ready', readyAt: 3000 },
        {
          ...task,
          id: 'blocked',
          state: 'blocked',
          blockedReason: 'process cap = 1',
          currentAttempt: 1,
          attempts: [
            {
              number: 1,
              entryId: 'entry',
              agentProfileId: 'agent',
              modelId: 'model',
              kind: 'external',
              state: 'uncertain',
              startedAt: 1000,
              usage: {
                inputTokens: 100,
                cachedInputTokens: 50,
                outputTokens: 20,
                reasoningTokens: 10,
                modelCalls: 1,
                costUsd: 1,
                accuracy: 'estimated',
              },
            },
          ],
        },
      ],
    },
    ranks: [
      { taskId: 'ready-two', priority: 4, criticalPath: 2, fit: 1, score: 8 },
      { taskId: 'ready-one', priority: 2, criticalPath: 1, fit: 0.5, score: 1 },
    ],
    entries: [
      { id: 'entry', generation: 1, roleId: 'engineering', label: 'model · agent' },
      { id: 'other-entry', generation: 1, roleId: 'engineering', label: 'other model' },
      { id: 'docs-entry', generation: 1, roleId: 'docs', label: 'docs model' },
    ],
    taskActions: [
      {
        taskId: 'ready-one',
        attempt: 0,
        generation: 1,
        actions: ['runNext', 'hold', 'priority', 'reassign', 'cancel'],
      },
      {
        taskId: 'ready-two',
        attempt: 0,
        generation: 1,
        actions: ['runNext', 'hold', 'release', 'cancel'],
      },
      {
        taskId: 'blocked',
        attempt: 1,
        generation: 1,
        actions: ['continueAnyway', 'restartTeamHost', 'raiseLimit'],
        reason: 'process cap = 1; browser held',
      },
    ],
    lanes: [
      { id: 'engineering', label: 'engineering', scope: 'role', busy: 1, capacity: 2 },
      { id: 'runner', label: 'macmini', scope: 'runner', busy: 2, capacity: 3 },
    ],
    hostBusy: false,
    writeLeases: [
      {
        workspaceId: 'workspace',
        holder: { taskId: 'blocked', attempt: 1 },
        paths: ['src/a.ts'],
        exclusiveWriter: true,
      },
    ],
    resources: [
      {
        id: 'browser',
        generation: 1,
        holder: 'blocked',
        waiters: ['ready-one'],
        actions: ['takeBack', 'restartServer', 'releaseAnyway'],
      },
    ],
    windows: [
      {
        windowInstanceId: 'peer-one',
        workspace: 'Other workspace',
        branches: ['feature/a'],
        paths: ['src/a.ts'],
        servers: ['browser'],
        fresh: true,
        workers: 3,
        processWorkers: 1,
        heavyCommands: 1,
      },
      {
        windowInstanceId: 'peer-two',
        workspace: 'Another workspace',
        branches: ['feature/b'],
        paths: [],
        servers: [],
        fresh: true,
        workers: 4,
        processWorkers: 2,
        heavyCommands: 0,
      },
      {
        windowInstanceId: 'stale-peer',
        workspace: 'Old workspace',
        branches: [],
        paths: [],
        servers: [],
        fresh: false,
        workers: 100,
        processWorkers: 0,
        heavyCommands: 0,
      },
    ],
    localWorkers: 2,
    workerCap: 8,
    recovery: [
      {
        id: 'interrupted',
        generation: 1,
        kind: 'interrupted',
        taskId: 'blocked',
        attempt: 1,
        ownerMayBeLive: true,
        windowInstanceId: 'peer-one',
        paths: ['src/a.ts'],
        detail: 'Task interrupted; another window may be open.',
        actions: ['newTask', 'openWindow', 'takeOver', 'resume', 'discard'],
      },
      {
        id: 'landing',
        generation: 1,
        kind: 'landing',
        ownerMayBeLive: false,
        lockPath: '.git/index.lock',
        paths: ['src/a.ts'],
        detail: 'Open landing journal',
        actions: ['recover', 'showTerminal'],
      },
      {
        id: 'orphan',
        generation: 1,
        kind: 'orphan',
        ownerMayBeLive: false,
        pid: 123,
        launchId: 'launch-one',
        match: 'uncertain',
        startedAt: 1000,
        paths: [],
        detail: 'node worker',
        actions: ['stop', 'keep', 'showTerminal'],
      },
    ],
    conflicts: [
      {
        id: 'conflict',
        generation: 1,
        taskIds: ['ready-one', 'blocked'],
        paths: ['src/a.ts'],
        actions: ['serialize', 'letBothRun'],
      },
    ],
    mergeQueue: [
      {
        taskId: 'ready-one',
        position: 1,
        generation: 1,
        reason: 'dependency → priority → conflicts → blast radius → finish',
        state: 'serial',
        checkLocation: 'macmini',
        flaky: true,
        actions: [
          'retry',
          'remove',
          'landNow',
          'landWithoutChecks',
          'apply',
          'undoBatch',
          'openTerminal',
        ],
        landingBranch: 'agents/landing/one',
      },
    ],
    mergePaused: false,
    copies: [
      { taskId: 'landed', generation: 1, state: 'merged', bytes: 10_000 },
      { taskId: 'discarded', generation: 1, state: 'discarded', bytes: 5000 },
      { taskId: 'unmerged', generation: 1, state: 'unmerged', bytes: 1000 },
      { taskId: 'quarantined', generation: 1, state: 'quarantined', bytes: 1000 },
    ],
    metrics: ['today', 'week', 'allTime'].map((period) => ({
      period,
      roleId: 'engineering',
      busySlotMs: 1000,
      availableSlotMs: 2000,
      queueDepth: [{ at: 1000, ready: 2, blocked: 1 }],
      waitMedianMs: 1000,
      waitP90Ms: 2000,
      writingTasks: 2,
      taskCount: 4,
      predictedConflicts: 1,
      landings: 1,
      mergeConflicts: 0,
      reworkRounds: 1,
      reassignments: 1,
      candidatesReturned: 1,
      mergedChanges: 1,
      reportedCostUsd: 2,
      estimatedCostUsd: 1,
      reportedTokens: 120,
      estimatedTokens: 100,
      timeToMergeMedianMs: 3000,
    })),
    announcements: [],
  })
}
export function runnersFixture() {
  return runnersSliceSchema.parse({
    trusted: true,
    runners: [
      {
        id: 'macmini',
        destination: 'macmini',
        os: 'darwin',
        workFolder: '/tmp/muse-runs',
        maxJobs: 3,
        labels: ['os:darwin'],
        commandClasses: ['tests', 'builds', 'typeChecks'],
        setupCommand: 'npm ci',
        cacheKey: 'package-lock',
        environmentNames: ['CI'],
      },
    ],
    health: [
      {
        id: 'macmini',
        state: 'testFailed',
        fingerprint: 'SHA256:fixture-host',
        inputHang: true,
        detail: 'remote shell waited for input',
      },
    ],
  })
}
