// Compatibility entry for lane T's consumers; lane 0 owns the tunables.
export {
  TEAM_IDENTIFIER_MAX_CHARS,
  TEAM_REASON_MAX_CHARS,
  TEAM_PLAN_ITEM_MAX_CHARS,
  TEAM_PATH_MAX_CHARS,
  TEAM_FILES_MAX,
  TEAM_PLAN_ITEMS_MAX,
  TEAM_TASK_IDS_MAX,
  TEAM_DELEGATE_MAX,
  TEAM_COLLECT_PAGE_CHARS,
  TEAM_COLLECT_WAIT_MAX_SECONDS,
  TEAM_BRIEF_MAX_CHARS,
  TEAM_BRIEF_FILES_MAX_BYTES,
  TEAM_MCP_TOKEN_BYTES,
  type TeamReasonCode,
} from '../../shared/constants'
