// M91 lane X: the plugin child's entry source. It runs OUT OF PROCESS under
// the user's own runtime (system node >= 22.18 for Amp/plain JS, with TS
// through Node's built-in type stripping; the user's bun for OpenCode) and
// never in the extension host. pluginHost.ts spawns
// `<runtime> -e <this source>` with one JSON request on stdin and reads one
// JSON line on stdout: { ok: true, answer, refused? } or { ok: false, error }.
// The shims expose only the hook subset from PLAN's lane X mapping:
// - Amp: the plugin's default export receives `amp`; amp.on(event, handler)
//   for the 5 mapped events, with a restricted ctx; any other event is
//   refused by name (`refused`). Of the helpers, only
//   shellCommandFromToolCall is offered, as pure data.
// - OpenCode: every exported plugin function, in load order, with the typed
//   hooks and the event-bus subset from the mapping; any other returned hook
//   is refused by name.
// No shell runner, no client, no model access: touching one throws, which
// fails that hook. Plain JS only (no TS syntax): the entry itself must run
// on both runtimes without stripping.
const CHILD_LINES = [
  "'use strict';",
  'const chunks = [];',
  'process.stdin.on("data", (c) => { chunks.push(c); });',
  'process.stdin.on("end", () => { void main(Buffer.concat(chunks).toString("utf8")); });',
  'function fail(error) {',
  String.raw`  process.stdout.write(JSON.stringify({ ok: false, error: String(error && error.message || error) }) + "\n");`,
  '  process.exitCode = 1;',
  '}',
  '// Registrations the mapping refuses: reported by name, the host owns the reasons.',
  'const refusedNames = [];',
  'function refuse(name) { if (!refusedNames.includes(name)) refusedNames.push(String(name)); }',
  'async function main(text) {',
  '  let request;',
  '  try { request = JSON.parse(text); } catch (e) { fail("bad request"); return; }',
  '  silenceConsole();',
  '  try {',
  '    const answer = request.system === "amp" ? await runAmp(request) : await runOpenCode(request);',
  '    const frame = refusedNames.length > 0 ? { ok: true, answer, refused: refusedNames } : { ok: true, answer };',
  String.raw`    process.stdout.write(JSON.stringify(frame) + "\n");`,
  '  } catch (e) { fail(e); }',
  '}',
  '// Plugin stdout must stay one JSON line: anything a plugin logs goes to stderr.',
  'function silenceConsole() {',
  '  for (const name of ["log", "info", "warn", "error", "debug"]) {',
  String.raw`    console[name] = (...args) => { process.stderr.write(args.map(String).join(" ") + "\n"); };`,
  '  }',
  '}',
  'function refused(name) {',
  '  const error = new Error("plugin shim: " + name + " is not offered");',
  '  error.code = "PLUGIN_NOT_OFFERED";',
  '  throw error;',
  '}',
  'function throwing(name) {',
  '  return new Proxy(function () {}, {',
  '    get: (_t, _p) => refused(name),',
  '    apply: () => refused(name),',
  '    construct: () => refused(name),',
  '  });',
  '}',
  'function noopLogger() {',
  '  const noop = () => {};',
  '  return { log: noop, warn: noop, error: noop, debug: noop };',
  '}',
  'async function importPlugin(plugin) {',
  '  const { pathToFileURL } = await import("node:url");',
  '  return import(pathToFileURL(plugin).href);',
  '}',
  '// --- Amp (raw/amp_plugin-api.md; the default export, amp_customize_plugins.md:111-122) ---',
  'const AMP_EVENTS = ["session.start", "tool.call", "tool.result", "agent.start", "agent.end"];',
  'function strictApi(name, offered) {',
  '  return new Proxy({}, { get: (_t, prop) => {',
  '    if (typeof prop === "string" && Object.hasOwn(offered, prop)) return offered[prop];',
  '    if (typeof prop !== "string") return undefined;',
  '    refused(name + "." + String(prop));',
  '  } });',
  '}',
  '// amp.helpers.shellCommandFromToolCall (amp_plugin-api.md:2262-2278), offered as pure data:',
  '// a Bash or shell_command call gives its command, anything else null. No process, no shell.',
  'function shellCommandFromToolCall(event) {',
  '  if (!event || typeof event !== "object" || (event.tool !== "Bash" && event.tool !== "shell_command")) return null;',
  '  const input = event.input;',
  '  if (!input || typeof input !== "object" || typeof input.command !== "string") return null;',
  '  return { command: input.command };',
  '}',
  'async function runAmp(request) {',
  '  if (!AMP_EVENTS.includes(request.hook)) throw new Error("amp: unsupported event " + request.hook);',
  '  const handlers = {};',
  '  // The PluginAPI the default export receives (amp_plugin-api.md:524-566).',
  '  const amp = strictApi("amp", {',
  '    on: (event, handler) => {',
  '      if (typeof handler !== "function") throw new Error("amp.on needs a handler");',
  '      if (!AMP_EVENTS.includes(event)) { refuse(event); return { unsubscribe: () => {} }; }',
  '      const list = (handlers[event] = handlers[event] || []);',
  '      list.push(handler);',
  '      return { unsubscribe: () => { const at = list.indexOf(handler); if (at !== -1) list.splice(at, 1); } };',
  '    },',
  '    logger: noopLogger(),',
  '    helpers: strictApi("amp.helpers", { shellCommandFromToolCall }),',
  '  });',
  '  const mod = await importPlugin(request.plugin);',
  '  if (!mod || typeof mod.default !== "function") throw new Error("amp: the plugin has no default export function");',
  '  await mod.default(amp);',
  '  const fns = handlers[request.hook] || [];',
  '  if (fns.length === 0) return { status: "completed" };',
  '  const payload = request.payload || {};',
  '  const ctx = strictApi("ctx", { thread: payload.thread || { id: "" }, logger: noopLogger() });',
  '  let failure = null;',
  '  let updatedInput = null;',
  '  let replacement = null;',
  '  const contexts = [];',
  '  // A veto ends the chain and stands: no later handler, failing or not, can erase it.',
  '  // A failure does not end it: a later handler may still veto.',
  '  for (const fn of fns) {',
  '    let result;',
  '    try {',
  '      result = await fn(ampEvent(request.hook, payload), ctx);',
  '    } catch (e) { failure = failure || { status: "failed", reason: ampReason(e) }; continue; }',
  '    const answer = interpretAmp(request.hook, result);',
  '    if (answer.status === "blocked") return answer;',
  '    if (answer.status === "failed") { failure = failure || answer; continue; }',
  '    if (answer.updatedInput !== undefined && updatedInput === null) updatedInput = answer.updatedInput;',
  '    if (answer.replacement !== undefined && replacement === null) replacement = answer.replacement;',
  '    if (answer.context !== undefined) contexts.push(answer.context);',
  '  }',
  '  if (failure !== null) return failure;',
  '  const merged = { status: "completed" };',
  '  if (updatedInput !== null) merged.updatedInput = updatedInput;',
  '  if (replacement !== null) merged.replacement = replacement;',
  String.raw`  if (contexts.length > 0) merged.context = contexts.join("\n");`,
  '  return merged;',
  '}',
  '// Each event with every field its type requires (amp_plugin-api.md:1929-2135).',
  'function ampEvent(hook, payload) {',
  '  if (hook === "session.start") return { thread: payload.thread };',
  '  if (hook === "tool.call") return { toolUseID: payload.toolUseID, tool: payload.tool, input: payload.input, thread: payload.thread };',
  '  if (hook === "tool.result") return { toolUseID: payload.toolUseID, tool: payload.tool, input: payload.input, status: payload.status, output: payload.output, error: payload.error, thread: payload.thread };',
  '  if (hook === "agent.start") return { thread: payload.thread, message: payload.message, id: payload.id };',
  '  return { thread: payload.thread, message: payload.message, id: payload.id, status: payload.status, messages: Array.isArray(payload.messages) ? payload.messages : [] };',
  '}',
  'function ampReason(e) {',
  '  const message = e && e.message ? String(e.message) : String(e);',
  '  return message === "" ? "plugin failed" : message;',
  '}',
  'function invalid(what) { return { status: "failed", reason: "amp plugin returned an invalid " + what }; }',
  '// PLAN lane X mapping: allow is completed (never a grant).',
  'function interpretAmp(hook, result) {',
  '  if (result === undefined || result === null) return { status: "completed" };',
  '  if (hook === "session.start") return { status: "completed" };',
  '  if (hook === "tool.call") {',
  '    if (typeof result !== "object" || typeof result.action !== "string") return invalid("tool.call result");',
  '    if (result.action === "allow") return { status: "completed" };',
  '    if (result.action === "reject-and-continue") {',
  '      if (typeof result.message !== "string" || result.message === "") return invalid("tool.call rejection");',
  '      return { status: "blocked", reason: result.message };',
  '    }',
  '    if (result.action === "modify") {',
  '      if (typeof result.input !== "object" || result.input === null || Array.isArray(result.input)) return invalid("tool.call input");',
  '      return { status: "completed", updatedInput: result.input };',
  '    }',
  '    if (result.action === "synthesize") {',
  '      const synthesized = result.result;',
  '      if (typeof synthesized !== "object" || synthesized === null || typeof synthesized.output !== "string") return invalid("tool.call result");',
  '      return { status: "completed", replacement: { target: "toolResult", value: { output: synthesized.output } } };',
  '    }',
  '    // amp_plugin-api.md:1978: `error` stops the thread worker, so the tool never',
  "    // runs and the turn ends with the plugin's reason; a refusal, not a failure.",
  '    if (result.action === "error") {',
  '      if (typeof result.message !== "string" || result.message === "") return invalid("tool.call error");',
  '      return { status: "blocked", reason: result.message, stopReason: result.message };',
  '    }',
  '    return invalid("tool.call result");',
  '  }',
  '  if (hook === "tool.result") {',
  '    if (typeof result !== "object") return invalid("tool.result result");',
  '    if (result.status !== "done" && result.status !== "error" && result.status !== "cancelled") return invalid("tool.result result");',
  '    return { status: "completed", replacement: { target: "toolResult", value: { status: result.status, output: result.output, error: result.error } } };',
  '  }',
  '  if (hook === "agent.start") {',
  '    if (typeof result !== "object") return invalid("agent.start result");',
  '    const message = result.message;',
  '    if (message === undefined) return { status: "completed" };',
  '    if (typeof message !== "object" || message === null || typeof message.content !== "string") return invalid("agent.start message");',
  '    return { status: "completed", context: message.content };',
  '  }',
  '  if (typeof result !== "object") return invalid("agent.end result");',
  '  if (result.action === undefined) return { status: "completed" };',
  '  if (result.action !== "continue" || typeof result.userMessage !== "string" || result.userMessage === "") return invalid("agent.end result");',
  '  // A continue keeps the turn going with the user message (a Stop block), never a stop.',
  '  return { status: "blocked", reason: result.userMessage };',
  '}',
  '// --- OpenCode (raw/oc_plugin_index.ts; a module exports one or more plugin functions, raw/oc_plugins.mdx:66-70) ---',
  '// The hooks PLAN.md M91 maps; every other returned key is refused by name.',
  'const OPENCODE_HOOKS = ["event", "tool.execute.before", "tool.execute.after", "permission.ask", "command.execute.before", "chat.message", "experimental.session.compacting"];',
  'async function runOpenCode(request) {',
  '  const mod = await importPlugin(request.plugin);',
  '  const factories = [];',
  '  for (const value of Object.values(mod || {})) if (typeof value === "function" && !factories.includes(value)) factories.push(value);',
  '  if (factories.length === 0) throw new Error("opencode: the module exports no plugin function");',
  '  const payload = request.payload || {};',
  '  const input = {',
  '    client: throwing("client"),',
  '    project: {},',
  '    directory: typeof payload.directory === "string" ? payload.directory : "",',
  '    worktree: "",',
  '    serverUrl: "",',
  '    $: throwing("shell"),',
  '    experimental_workspace: { register: () => refused("workspace") },',
  '  };',
  '  const handlers = [];',
  '  for (const factory of factories) {',
  '    const hooks = await factory(input);',
  '    if (!hooks || typeof hooks !== "object") continue;',
  '    for (const key of Object.keys(hooks)) if (!OPENCODE_HOOKS.includes(key)) refuse(key);',
  '    if (typeof hooks[request.hook] === "function") handlers.push(hooks[request.hook]);',
  '  }',
  '  if (request.hook === "event") return runBusEvent(handlers, payload);',
  '  if (request.hook === "tool.execute.before") return runBefore(handlers, payload);',
  '  if (request.hook === "tool.execute.after") return runAfter(handlers, payload);',
  '  if (request.hook === "permission.ask") return runAsk(handlers, payload);',
  '  if (request.hook === "command.execute.before") return runCommand(handlers, payload);',
  '  if (request.hook === "chat.message") return runChatMessage(handlers, payload);',
  '  if (request.hook === "experimental.session.compacting") return runCompacting(handlers, payload);',
  '  throw new Error("opencode: unsupported hook " + request.hook);',
  '}',
  '// Each handler sees the same output object, in load order, as OpenCode passes it on.',
  'async function runBefore(handlers, payload) {',
  '  if (handlers.length === 0) return { status: "completed" };',
  '  // A copy: a plugin that rewrites output.args in place (oc_plugins.mdx:91-99) must',
  '  // not rewrite the original it is compared with.',
  '  const output = { args: payload.args === undefined ? undefined : structuredClone(payload.args) };',
  '  for (const fn of handlers) {',
  '    try {',
  '      await fn({ tool: payload.tool, sessionID: payload.sessionID, callID: payload.callID }, output);',
  '    } catch (e) { return { status: "blocked", reason: ampReason(e) }; }',
  '  }',
  '  if (JSON.stringify(output.args) === JSON.stringify(payload.args)) return { status: "completed" };',
  '  if (!output.args || typeof output.args !== "object" || Array.isArray(output.args)) return { status: "failed", reason: "opencode: the rewritten args are not an object" };',
  '  return { status: "completed", updatedInput: output.args };',
  '}',
  'async function runAfter(handlers, payload) {',
  '  if (handlers.length === 0) return { status: "completed" };',
  '  const output = { title: "", output: payload.output, metadata: {} };',
  '  for (const fn of handlers) {',
  '    try {',
  '      await fn({ tool: payload.tool, sessionID: payload.sessionID, callID: payload.callID, args: structuredClone(payload.args) }, output);',
  '    } catch (e) { return { status: "failed", reason: ampReason(e) }; }',
  '  }',
  '  if (output.output === payload.output) return { status: "completed" };',
  '  if (typeof output.output !== "string") return { status: "failed", reason: "opencode: tool output replacement must be a string" };',
  '  return { status: "completed", replacement: { target: "toolResult", value: output.output } };',
  '}',
  'async function runAsk(handlers, payload) {',
  '  if (handlers.length === 0) return { status: "completed" };',
  '  const output = { status: "ask" };',
  '  for (const fn of handlers) {',
  '    try {',
  '      await fn(structuredClone(payload.permission || {}), output);',
  '    } catch (e) { return { status: "failed", reason: ampReason(e) }; }',
  '  }',
  '  if (output.status === "deny") return { status: "blocked", reason: "opencode plugin denied the call", approvalDecision: "deny" };',
  '  if (output.status === "ask") return { status: "completed", permissionDecision: "ask" };',
  '  if (output.status === "allow") return { status: "completed" };',
  '  return { status: "failed", reason: "opencode: permission status must be ask, deny or allow" };',
  '}',
  'async function runCommand(handlers, payload) {',
  '  const output = { parts: [] };',
  '  for (const fn of handlers) {',
  '    try {',
  '      await fn({ command: payload.command, sessionID: payload.sessionID, arguments: payload.arguments }, output);',
  '    } catch (e) { return { status: "blocked", reason: ampReason(e) }; }',
  '  }',
  '  return { status: "completed" };',
  '}',
  'async function runChatMessage(handlers, payload) {',
  '  // Observation only: a rewritten message is not applied (PLAN.md M91).',
  '  const output = { message: structuredClone(payload.message || {}), parts: structuredClone(payload.parts || []) };',
  '  for (const fn of handlers) {',
  '    try {',
  '      await fn({ sessionID: payload.sessionID }, output);',
  '    } catch (e) { return { status: "failed", reason: ampReason(e) }; }',
  '  }',
  '  return { status: "completed" };',
  '}',
  'async function runCompacting(handlers, payload) {',
  '  const output = { context: [], prompt: undefined };',
  '  for (const fn of handlers) {',
  '    try {',
  '      await fn({ sessionID: payload.sessionID }, output);',
  '    } catch (e) { return { status: "failed", reason: ampReason(e) }; }',
  '  }',
  '  const lines = Array.isArray(output.context) ? output.context.filter((line) => typeof line === "string") : [];',
  '  if (lines.length === 0) return { status: "completed" };',
  String.raw`  return { status: "completed", context: lines.join("\n") };`,
  '}',
  'async function runBusEvent(handlers, payload) {',
  '  let failure = null;',
  '  for (const fn of handlers) {',
  '    try {',
  '      await fn({ event: Object.freeze(structuredClone(payload.event || {})) });',
  '    } catch (e) { failure = failure || { status: "failed", reason: ampReason(e) }; }',
  '  }',
  '  return failure || { status: "completed" };',
  '}',
]

/** The entry source pluginHost.ts spawns. Joined here so the host, the tests
 * and (later) the bundle all read the same bytes. */
export function pluginChildSource(): string {
  return CHILD_LINES.join('\n')
}
