// HELPREF: reviewed feature relationships. The generator validates every id
// against the manifest and reuses its translated text and the palette's tips.
import { COMMAND_IDS } from './constants'
import type { UiText } from './l10n/en'

export type ReferenceText =
  | { readonly ui: { [K in keyof UiText]: UiText[K] extends string ? K : never }[keyof UiText] }
  | { readonly tip: keyof UiText['paletteTips'] }
  | { readonly setting: string }
  | { readonly command: string }

interface Feature {
  readonly id: string
  readonly name: ReferenceText
  readonly summary: ReferenceText
  readonly description: ReferenceText
  readonly commands: readonly string[]
  readonly settings: readonly string[]
  readonly docs: string
  readonly editors: readonly ('vscode' | 'acp')[]
  readonly backends: readonly ('museCode' | 'modelApi')[]
  readonly paid: boolean
}

type CommandKey = keyof typeof COMMAND_IDS
interface CommandReference {
  readonly description: ReferenceText
  /** No spending, destructive change, or dependence on a chat/editor selection. */
  readonly canRun: boolean
}

export const COMMAND_REFERENCE: Readonly<Record<CommandKey, CommandReference>> = {
  openInSidebar: { description: { ui: 'referenceSidebar' }, canRun: true },
  openInNewTab: { description: { ui: 'referenceNewTab' }, canRun: true },
  focusInput: { description: { ui: 'referenceFocus' }, canRun: false },
  openTasks: { description: { ui: 'referenceTasks' }, canRun: false },
  insertMentionReference: { description: { tip: 'mentionFile' }, canRun: false },
  toggleFocusView: { description: { tip: 'focusView' }, canRun: false },
  toggleThinking: { description: { tip: 'thinking' }, canRun: false },
  setUpSandbox: { description: { setting: 'shellSandbox' }, canRun: false },
  showLogs: { description: { tip: 'log' }, canRun: true },
  diagnostics: { description: { ui: 'referenceDiagnostics' }, canRun: true },
  reportProblem: { description: { ui: 'referenceReport' }, canRun: true },
  newConversation: { description: { tip: 'clear' }, canRun: false },
  signOut: { description: { tip: 'signOut' }, canRun: false },
  openInTerminal: { description: { ui: 'referenceTerminal' }, canRun: false },
  createRulesFile: { description: { ui: 'referenceRules' }, canRun: false },
  openWalkthrough: { description: { ui: 'referenceWalkthrough' }, canRun: true },
  manageSkills: { description: { tip: 'manageSkills' }, canRun: false },
  importSkills: { description: { tip: 'importSkills' }, canRun: false },
  importFromAgents: { description: { tip: 'importFromAgents' }, canRun: false },
  exportConversation: { description: { tip: 'export' }, canRun: false },
  importSession: { description: { tip: 'importSession' }, canRun: false },
  openShareFile: { description: { tip: 'openShare' }, canRun: true },
  mcpServers: { description: { ui: 'mcpItemDetailModelApi' }, canRun: true },
  hooks: { description: { tip: 'hooks' }, canRun: true },
  runSetupHooks: { description: { ui: 'manualHookSlashDetail' }, canRun: false },
  runHook: { description: { tip: 'hookRun' }, canRun: false },
  retryPluginHooks: { description: { ui: 'referenceRetry' }, canRun: false },
  memory: { description: { tip: 'memory' }, canRun: true },
  newWorktree: { description: { tip: 'newWorktree' }, canRun: false },
  removeWorktree: { description: { tip: 'removeWorktree' }, canRun: false },
  moveToBackground: { description: { ui: 'moveToBackgroundTitle' }, canRun: false },
  stopBackgroundTasks: { description: { ui: 'stopAllTasksTitle' }, canRun: false },
  restartMuseCode: { description: { ui: 'mcpRestartDetail' }, canRun: false },
  installBundledSkills: { description: { setting: 'bundledSkills' }, canRun: false },
  removeBundledSkills: { description: { setting: 'bundledSkills' }, canRun: false },
  downloadBrowserCheckRuntime: { description: { setting: 'browserCheckRuntime' }, canRun: false },
  showWhatsNew: { description: { tip: 'whatsNew' }, canRun: true },
  tabTurnOn: { description: { setting: 'modelApiTab' }, canRun: false },
  tabTurnOff: { description: { setting: 'modelApiTab' }, canRun: false },
  tabSnooze: { description: { ui: 'tabMenuSnoozeShort' }, canRun: false },
  tabMenu: { description: { setting: 'modelApiTab' }, canRun: true },
  tabLanguages: { description: { setting: 'tabLanguages' }, canRun: false },
  openPullRequestInConversation: { description: { ui: 'gitCheckoutItemDetail' }, canRun: false },
  openHelp: { description: { ui: 'referenceIntro' }, canRun: true },
}

function feature(
  id: string,
  name: ReferenceText,
  summary: ReferenceText,
  commands: readonly CommandKey[],
  settings: readonly string[],
  docs: string,
  backends: Feature['backends'] = ['museCode', 'modelApi'],
  isPaid = false,
  editors: Feature['editors'] = ['vscode', 'acp'],
): Feature {
  return {
    id,
    name,
    summary,
    description: settings[0] === undefined ? summary : { setting: settings[0] },
    commands: commands.map((key) => COMMAND_IDS[key]),
    settings: settings.map((key) => `museSpark.${key}`),
    docs: `https://github.com/RandyNorthrup/muse-spark-code#${docs}`,
    backends,
    paid: isPaid,
    editors,
  }
}

export function featureCatalog(): readonly Feature[] {
  return [
    feature(
      'web-fetch',
      { ui: 'referenceWebFetchTitle' },
      { ui: 'referenceWebFetchDetail' },
      [],
      [],
      'web-fetch',
    ),
    feature(
      'code-intelligence',
      { ui: 'referenceCodeIntelTitle' },
      { ui: 'referenceCodeIntelDetail' },
      [],
      [],
      'code-intelligence',
      undefined,
      false,
      ['vscode'],
    ),
    feature('shell', { ui: 'composerShellMode' }, { ui: 'referenceShellDetail' }, [], [], 'tasks'),
    feature(
      'session-board',
      { ui: 'boardTitle' },
      { ui: 'referenceBoardDetail' },
      [],
      [],
      'session-board-and-best-of-n',
      undefined,
      false,
      ['vscode'],
    ),
    feature(
      'edit-review',
      { ui: 'reviewChangesItem' },
      { ui: 'reviewChangesDetail' },
      [],
      [],
      'review',
      undefined,
      false,
      ['vscode'],
    ),
    feature(
      'free-dictation',
      { ui: 'dictationLabel' },
      { setting: 'dictationEngine' },
      [],
      [],
      'voice-dictation',
      undefined,
      false,
      ['vscode'],
    ),
    feature(
      'chat',
      { ui: 'transcriptLabel' },
      { ui: 'referenceNewTab' },
      [
        'openInSidebar',
        'openInNewTab',
        'focusInput',
        'newConversation',
        'insertMentionReference',
        'toggleFocusView',
        'toggleThinking',
      ],
      [
        'preferredLocation',
        'autosave',
        'attachOpenFile',
        'useCtrlEnterToSend',
        'hideOnboarding',
        'focusView',
        'enableNewConversationShortcut',
      ],
      'the-panel',
      undefined,
      false,
      ['vscode'],
    ),
    feature(
      'account',
      { ui: 'groupAccount' },
      { tip: 'accountUsage' },
      ['signOut', 'restartMuseCode', 'openInTerminal'],
      [
        'backend',
        'museBinaryPath',
        'environmentVariables',
        'modelApiReplyUsage',
        'modelApiSessionBudgetUsd',
        'confidentialWorkspace',
      ],
      'get-started',
    ),
    feature(
      'permissions',
      { ui: 'permissionModeItem' },
      { tip: 'permissionMode' },
      ['setUpSandbox'],
      [
        'initialPermissionMode',
        'allowDangerouslySkipPermissions',
        'shellSandbox',
        'sandboxNetwork',
      ],
      'permission-modes',
    ),
    feature(
      'history',
      { ui: 'resumeItem' },
      { tip: 'resume' },
      [],
      ['archiveInactiveSessions', 'cleanupPeriodDays'],
      'the-panel',
    ),
    feature(
      'context',
      { ui: 'mentionFile' },
      { tip: 'mentionFile' },
      ['createRulesFile'],
      ['respectGitIgnore'],
      'rules-skills-and-memory',
    ),
    feature(
      'skills',
      { ui: 'groupSkills' },
      { tip: 'manageSkills' },
      ['manageSkills', 'importSkills', 'installBundledSkills', 'removeBundledSkills'],
      ['bundledSkills'],
      'bundled-skills',
    ),
    feature(
      'imports',
      { command: COMMAND_IDS.importFromAgents },
      { tip: 'importFromAgents' },
      ['importFromAgents'],
      [],
      'rules-skills-and-memory',
    ),
    feature('memory', { ui: 'memoryItem' }, { tip: 'memory' }, ['memory'], [], 'memory'),
    feature(
      'mcp',
      { ui: 'mcpItem' },
      { ui: 'mcpItemDetailModelApi' },
      ['mcpServers'],
      [],
      'rules-skills-and-memory',
    ),
    feature(
      'hooks',
      { ui: 'hooksItem' },
      { ui: 'hooksItemDetail' },
      ['hooks', 'runSetupHooks', 'runHook', 'retryPluginHooks'],
      ['modelApiHooks', 'hookHttpAllowedHosts', 'modelApiShellKeepsDirectory'],
      'hooks',
    ),
    feature(
      'git',
      { ui: 'groupGit' },
      { tip: 'newWorktree' },
      ['newWorktree', 'removeWorktree', 'openPullRequestInConversation'],
      [],
      'git-and-pull-requests',
    ),
    feature(
      'tasks',
      { ui: 'backgroundTasksLabel' },
      { ui: 'moveToBackgroundTitle' },
      ['openTasks', 'moveToBackground', 'stopBackgroundTasks'],
      ['notifyOnBackgroundTurn'],
      'tasks',
    ),
    feature(
      'exports',
      { ui: 'exportJsonItem' },
      { tip: 'exportJson' },
      ['exportConversation', 'importSession', 'openShareFile'],
      [],
      'the-panel',
    ),
    feature('review', { ui: 'groupReview' }, { tip: 'review' }, [], [], 'review'),
    feature('plans', { ui: 'plansItem' }, { tip: 'plans' }, [], [], 'plans-as-files'),
    feature('goals', { ui: 'goalItem' }, { tip: 'goal' }, [], [], 'session-goals'),
    feature(
      'handoff',
      { ui: 'handoffItem' },
      { tip: 'handoff' },
      [],
      [],
      'handoff-to-a-new-conversation',
    ),
    feature(
      'verify',
      { command: COMMAND_IDS.diagnostics },
      { setting: 'diagnosticsAfterEdits' },
      [],
      ['diagnosticsAfterEdits', 'checkCommands', 'formatOnEdit'],
      'checking-edits',
      ['modelApi'],
    ),
    feature(
      'repo-map',
      { setting: 'modelApiRepoMap' },
      { setting: 'modelApiRepoMap' },
      [],
      ['modelApiRepoMap', 'modelApiObservationPacking'],
      'code-intelligence',
      ['modelApi'],
    ),
    feature(
      'checkpoints',
      { setting: 'turnCheckpoints' },
      { setting: 'turnCheckpoints' },
      [],
      ['turnCheckpoints'],
      'the-panel',
      ['modelApi'],
    ),
    feature(
      'rules',
      { ui: 'permissionModeItem' },
      { setting: 'modelApiCommandRules' },
      [],
      [
        'modelApiCommandRules',
        'modelApiPermissionProfiles',
        'modelApiPermissionProfile',
        'modelApiRepositoryRules',
      ],
      'auto-rules-and-permission-profiles-model-api',
      ['modelApi'],
    ),
    feature(
      'browser',
      { command: COMMAND_IDS.downloadBrowserCheckRuntime },
      { setting: 'browserCheckRuntime' },
      ['downloadBrowserCheckRuntime'],
      ['browserCheckExtraHosts', 'browserCheckRuntime'],
      'browser-check',
      undefined,
      false,
      ['vscode'],
    ),
    feature(
      'voice',
      { ui: 'paidVoiceName' },
      { tip: 'paid:voice' },
      [],
      ['dictationEngine', 'modelApiVoice'],
      'voice-dictation',
      undefined,
      true,
      ['vscode'],
    ),
    feature(
      'search',
      { ui: 'paidWebSearchName' },
      { tip: 'paid:webSearch' },
      [],
      ['modelApiWebSearch'],
      'paid-features',
      ['modelApi'],
      true,
    ),
    feature(
      'images',
      { ui: 'paidImageGenerationName' },
      { tip: 'paid:imageGeneration' },
      [],
      ['modelApiImageGeneration'],
      'paid-features',
      undefined,
      true,
    ),
    feature(
      'schedules',
      { ui: 'loopItem' },
      { tip: 'loop' },
      [],
      ['modelApiScheduledPrompts'],
      'scheduled-prompts-model-api',
      ['modelApi'],
      true,
      ['vscode'],
    ),
    feature(
      'subagents',
      { ui: 'agentsCommand' },
      { tip: 'paid:subagents' },
      [],
      ['modelApiSubagents', 'modelApiBestOfN'],
      'session-board-and-best-of-n',
      ['modelApi'],
      true,
      ['vscode'],
    ),
    feature(
      'auto',
      { ui: 'permissionModeItem' },
      { tip: 'paid:autoReviewer' },
      [],
      ['modelApiAutoReviewer', 'museCodeAutoReviewer'],
      'auto-rules-and-permission-profiles-model-api',
      undefined,
      true,
      ['vscode'],
    ),
    feature(
      'hook-models',
      { ui: 'hooksItem' },
      { tip: 'paid:hookModels' },
      [],
      ['modelApiHookModels'],
      'hooks',
      ['modelApi'],
      true,
      ['vscode'],
    ),
    feature(
      'cache',
      { setting: 'modelApiPromptCacheRetention' },
      { setting: 'modelApiPromptCacheRetention' },
      [],
      ['modelApiPromptCacheRetention'],
      'paid-features',
      ['modelApi'],
      true,
      ['vscode'],
    ),
    feature(
      'budget',
      { setting: 'paidDailyBudgetUsd' },
      { setting: 'paidDailyBudgetUsd' },
      [],
      ['paidDailyBudgetUsd'],
      'paid-features',
      undefined,
      true,
    ),
    feature(
      'tab',
      { command: COMMAND_IDS.tabMenu },
      { setting: 'modelApiTab' },
      ['tabTurnOn', 'tabTurnOff', 'tabSnooze', 'tabMenu', 'tabLanguages'],
      [
        'modelApiTab',
        'tabModel',
        'tabDailyBudgetUsd',
        'tabLanguages',
        'tabMultiline',
        'tabTrigger',
        'tabWithCopilot',
      ],
      'tab-completions',
      undefined,
      true,
      ['vscode'],
    ),
    feature(
      'judge',
      { ui: 'paidJudgeName' },
      { tip: 'paid:judge' },
      [],
      ['judge.engine'],
      'muse-judge',
      ['modelApi'],
      true,
      ['vscode'],
    ),
    feature(
      'judge-subscription',
      { ui: 'paidJudgeName' },
      { ui: 'judgeSubscriptionNotice' },
      [],
      ['judge.engine'],
      'muse-judge',
      ['museCode'],
      false,
      ['vscode'],
    ),
    feature(
      'support',
      { ui: 'groupSupport' },
      { tip: 'issue' },
      ['showLogs', 'diagnostics', 'reportProblem', 'openWalkthrough', 'showWhatsNew', 'openHelp'],
      ['showWhatsNewOnUpdate'],
      'help-and-reference',
    ),
  ]
}
