// The Node bundles share only the zod/mini runtime API they use (PLAN.md D6).
// Browser and integration builds retain their inline parser. The split gate
// checks new member reads against these exports before the package can ship.
export {
  _default,
  array,
  boolean,
  discriminatedUnion,
  enum,
  exactOptional,
  extend,
  gt,
  gte,
  instanceof,
  int,
  iso,
  json,
  literal,
  looseObject,
  lte,
  maxLength,
  minLength,
  nonnegative,
  null,
  nullable,
  number,
  object,
  optional,
  partial,
  pipe,
  positive,
  prettifyError,
  safeParse,
  record,
  refine,
  regex,
  strictObject,
  string,
  transform,
  trim,
  union,
  unknown,
  url,
  uuid,
} from 'zod/mini'
