// The Node bundles share only the zod/mini runtime API they use (PLAN.md D6).
// Browser and integration builds retain their inline parser. The split gate
// checks new member reads against these exports before the package can ship.
export {
  _default,
  NEVER,
  nonoptional,
  custom,
  length,
  partialRecord,
  globalRegistry,
  ZodMiniArray,
  array,
  boolean,
  discriminatedUnion,
  // M91 lane M: an MCP form's email field.
  email,
  enum,
  exactOptional,
  extend,
  gt,
  gte,
  instanceof,
  int,
  iso,
  lazy,
  json,
  literal,
  looseObject,
  lte,
  maxLength,
  minLength,
  maximum,
  minimum,
  never,
  nonnegative,
  null,
  nullable,
  number,
  object,
  optional,
  partial,
  pipe,
  positive,
  prettifyError,
  safeParse,
  record,
  refine,
  regex,
  readonly,
  startsWith,
  strictObject,
  string,
  transform,
  trim,
  union,
  undefined,
  unknown,
  url,
  uuid,
} from 'zod/mini'
