// Check the exact generated bytes and every declared foreground/background
// use in all four Muse palettes. Text is 4.5:1; large text and UI are 3:1.
import { readFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import path from 'node:path'
import { TOKEN_SOURCE, parseTokens, renderTokens, resolveToken } from './build-tokens.mjs'

const TEXT_RATIO = 4.5
const UI_RATIO = 3
const SRGB_LINEAR_THRESHOLD = 0.04045
const SRGB_LINEAR_DIVISOR = 12.92
const SRGB_OFFSET = 0.055
const SRGB_SCALE = 1.055
const SRGB_EXPONENT = 2.4
const LUMINANCE_OFFSET = 0.05
const WHITE = { colorSpace: 'srgb', components: [1, 1, 1], alpha: 1 }

function rgb(colour) {
  if (colour.colorSpace === 'srgb') return colour.components
  // CSS Color 4's OKLab -> linear sRGB -> encoded sRGB conversion.
  const [l, chroma, hue] = colour.components
  const radians = (hue * Math.PI) / 180
  const a = chroma * Math.cos(radians)
  const b = chroma * Math.sin(radians)
  const ll = (l + 0.3963377774 * a + 0.2158037573 * b) ** 3
  const mm = (l - 0.1055613458 * a - 0.0638541728 * b) ** 3
  const ss = (l - 0.0894841775 * a - 1.291485548 * b) ** 3
  return [
    4.0767416621 * ll - 3.3077115913 * mm + 0.2309699292 * ss,
    -1.2684380046 * ll + 2.6097574011 * mm - 0.3413193965 * ss,
    -0.0041960863 * ll - 0.7034186147 * mm + 1.707614701 * ss,
  ].map((channel) =>
    Math.max(
      0,
      Math.min(
        1,
        channel <= 0.0031308
          ? channel * SRGB_LINEAR_DIVISOR
          : SRGB_SCALE * channel ** (1 / SRGB_EXPONENT) - SRGB_OFFSET,
      ),
    ),
  )
}

function over(foreground, background) {
  const alpha = foreground.alpha + background.alpha * (1 - foreground.alpha)
  if (alpha === 0) throw new Error('Contrast has no opaque canvas')
  const f = rgb(foreground)
  const b = rgb(background)
  return {
    colorSpace: 'srgb',
    alpha,
    components: f.map(
      (n, i) => (n * foreground.alpha + b[i] * background.alpha * (1 - foreground.alpha)) / alpha,
    ),
  }
}

function luminance(colour) {
  const linear = rgb(colour).map((n) =>
    n <= SRGB_LINEAR_THRESHOLD
      ? n / SRGB_LINEAR_DIVISOR
      : ((n + SRGB_OFFSET) / SRGB_SCALE) ** SRGB_EXPONENT,
  )
  return linear[0] * 0.2126 + linear[1] * 0.7152 + linear[2] * 0.0722
}

export function contrastRatio(foreground, background, canvas = WHITE) {
  if (canvas.alpha !== 1) throw new Error('Contrast canvas must be opaque')
  const bg = over(background, canvas)
  const fg = over(foreground, bg)
  const [lighter, darker] = [luminance(fg), luminance(bg)].toSorted((a, b) => b - a)
  return (lighter + LUMINANCE_OFFSET) / (darker + LUMINANCE_OFFSET)
}

// The generator emits sRGB as 8-bit hex (including alpha). Compare the
// actual emitted channels; rounding near 4.5:1 must never certify a failing pair.
function emittedColour(value) {
  if (value.colorSpace !== 'srgb') return value
  return {
    ...value,
    components: value.components.map((n) => Math.round(n * 255) / 255),
    alpha: Math.round(value.alpha * 255) / 255,
  }
}

export function checkContrast(input) {
  const { meta, tokens } = parseTokens(input)
  const problems = []
  const colourAt = (name, mode) => {
    if (tokens[name]?.$type !== 'color')
      throw new Error(`Contrast pair requires a colour token: ${name}`)
    return emittedColour(resolveToken(tokens, name, mode))
  }
  for (const mode of meta.modes)
    for (const pair of meta.contrastPairs) {
      const foreground = colourAt(pair.foreground, mode)
      const background = colourAt(pair.background, mode)
      if (background.alpha < 1 && pair.canvas === undefined) {
        throw new Error(`Alpha background needs an explicit canvas: ${pair.background}`)
      }
      const canvas = pair.canvas === undefined ? WHITE : colourAt(pair.canvas, mode)
      const ratio = contrastRatio(foreground, background, canvas)
      const required = pair.usage === 'text' ? TEXT_RATIO : UI_RATIO
      if (ratio < required)
        problems.push(
          `${mode}: ${pair.foreground} on ${pair.background}: ${ratio.toFixed(3)}:1 < ${required}:1 (${pair.usage})`,
        )
    }
  return problems
}

export async function checkTokens(root = process.cwd()) {
  const input = JSON.parse(await readFile(path.join(root, TOKEN_SOURCE), 'utf8'))
  const outputs = await renderTokens(input)
  const problems = checkContrast(input)
  for (const [file, expected] of Object.entries(outputs)) {
    let actual
    try {
      actual = await readFile(path.join(root, file), 'utf8')
    } catch (error) {
      if (error.code !== 'ENOENT') throw error
    }
    if (actual !== expected) problems.push(`Stale token output: ${file}; run npm run build:tokens`)
  }
  return problems
}

if (
  process.argv[1] !== undefined &&
  path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)
) {
  const problems = await checkTokens()
  for (const problem of problems) console.error(problem)
  console.log(`tokens: ${problems.length} problems`)
  if (problems.length > 0) process.exitCode = 1
}
