import { fill } from '../../shared/l10n/text'
import { UI_TEXT } from '../../shared/constants'
import { compareLegalText } from './files'
// Copyright headers and SPDX identifiers (M97, PLAN.md D76): per source
// file, under the header-policy setting. Shebangs, byte-order marks and
// editor mode lines are tolerated; generated files, REUSE declarations and
// license sidecars are honored, and the report names the generated
// exclusion. An earlier year alone is never stale; conflicting dates are.

import type { LegalHeaderPolicy } from '../../shared/constants'
import type { LegalFindingDraft } from './finding'
import type { LegalFileSnapshot } from './files'
import {
  baseNameOf,
  hasBinaryContent,
  excerpt,
  isLicenseFileName,
  topLines,
  isLegalGlobMatch,
} from './files'
import { orAlternatives, parseSpdxExpression } from './spdx'
import { parseTomlSection } from './ecosystems/toml'

/** What the header reader established, including named exclusions. */
export interface HeaderScanResult {
  readonly findings: readonly LegalFindingDraft[]
  readonly incomplete: readonly string[]
  /** Generated files excluded from header checks, for the report. */
  readonly excluded: readonly string[]
}

/** Source extensions whose top lines may carry a copyright header. */
const SOURCE_EXTENSIONS: ReadonlySet<string> = new Set([
  'ts',
  'tsx',
  'mts',
  'cts',
  'js',
  'jsx',
  'mjs',
  'cjs',
  'py',
  'pyi',
  'rb',
  'php',
  'cs',
  'java',
  'kt',
  'kts',
  'scala',
  'go',
  'rs',
  'c',
  'h',
  'cc',
  'cpp',
  'cxx',
  'hpp',
  'hh',
  'm',
  'mm',
  'swift',
  'sh',
  'bash',
  'ps1',
  'css',
  'scss',
  'less',
  'html',
  'vue',
  'svelte',
  'sql',
  'lua',
  'pl',
  'pm',
  'r',
  'jl',
  'ex',
  'exs',
  'erl',
])

/** Path segments and suffixes that mark generated output, not authorship. */
const GENERATED_SEGMENTS: ReadonlySet<string> = new Set([
  'dist',
  'build',
  'out',
  'coverage',
  'target',
  'obj',
  'gen',
  'generated',
  'node_modules',
  '.git',
])
const GENERATED_SUFFIXES = ['.min.js', '.bundle.js', '.chunk.js', '.gen.ts', '.g.ts']
const GENERATED_MARKER =
  /^\s*(?:\/\/|#|\/\*+|\*|<!--|--|;)\s*(?:@generated\b|auto-generated\b|do not (?:edit|modify)\b|generated by\b)/i

const COPYRIGHT_LINE =
  /^\s*(?:(?:\/\/|#|\/\*+|\*|<!--|--|;)\s*)?(?:copyright\s*(?:©|\(c\))?|SPDX-FileCopyrightText:)\s*(.+)/i
const YEAR_TOKEN = /\d{4}(?:\s*(?:-|–)\s*\d{2,4})?/g
const FOUR_DIGIT_YEAR = /^\d{4}$/
const YEAR_RANGE_SPLIT = /-|–/
const SPDX_LINE = /^\s*(?:(?:\/\/|#|\/\*+|\*|<!--|--|;)\s*)?SPDX-License-Identifier:\s*(.+?)\s*$/i
const COMMENT_TRAILER = /\s*(?:\*\/|-->)\s*$/

function isGeneratedPath(file: string): boolean {
  return (
    GENERATED_SUFFIXES.some((suffix) => file.endsWith(suffix)) ||
    file.split('/').some((segment) => GENERATED_SEGMENTS.has(segment.toLowerCase()))
  )
}

function isSourceFile(file: string): boolean {
  const base = baseNameOf(file)
  const dot = base.lastIndexOf('.')
  return dot !== -1 && SOURCE_EXTENSIONS.has(base.slice(dot + 1).toLowerCase())
}

interface HeaderEvidence {
  readonly copyrightLine: number | undefined
  readonly holder: string | undefined
  readonly spdxLine: number | undefined
  readonly spdxRaw: string | undefined
}

function readHeader(lines: string[]): HeaderEvidence {
  let copyrightLine: number | undefined
  let holder: string | undefined
  let spdxLine: number | undefined
  let spdxRaw: string | undefined
  const listed1 = lines.entries()
  for (const [index, line] of listed1) {
    if (copyrightLine === undefined) {
      const copyright = COPYRIGHT_LINE.exec(line)
      if (copyright?.[1] !== undefined) {
        copyrightLine = index + 1
        holder = copyright[1].replace(COMMENT_TRAILER, '').trim()
      }
    }
    if (spdxLine !== undefined) continue

    const spdx = SPDX_LINE.exec(line)
    if (spdx?.[1] === undefined) {
      continue
    }

    spdxLine = index + 1
    spdxRaw = spdx[1]
      .replace(COMMENT_TRAILER, '')
      .replace(/[,;*#]+$/, '')
      .trim()
  }
  return { copyrightLine, holder, spdxLine, spdxRaw }
}

function hasSidecarProvenance(sidecar: string | undefined): sidecar is string {
  if (sidecar === undefined) return false
  const declarations = topLines(sidecar).flatMap((line) => {
    const raw = readHeader([line]).spdxRaw
    return raw === undefined ? [] : [raw]
  })
  return (
    /SPDX-FileCopyrightText:\s*\S/.test(sidecar) &&
    declarations.length > 0 &&
    declarations.every((raw) => parseSpdxExpression(raw).ok)
  )
}

function expandEndYear(start: number, end: number): number {
  if (end >= 100) {
    return end
  }
  const century = Math.floor(start / 100) * 100
  const expanded = century + end
  return expanded < start ? expanded + 100 : expanded
}

/** Conflicting or impossible dates in a holder string, as one sentence. */
function dateProblem(holder: string): string | undefined {
  const tokens = holder.match(YEAR_TOKEN) ?? []
  for (const token of tokens) {
    const parts = token.split(YEAR_RANGE_SPLIT).map((part) => part.trim())
    const first = parts[0] ?? ''
    if (!FOUR_DIGIT_YEAR.test(first)) {
      return fill(UI_TEXT.legalScanner.invalidYear, { value: first })
    }
    const start = Number(first)
    if (start < 100) {
      return fill(UI_TEXT.legalScanner.impossibleYear, { value: first })
    }
    const second = parts[1] ?? ''
    if (second !== '' && expandEndYear(start, Number(second)) < start) {
      return fill(UI_TEXT.legalScanner.reversedYears, { value: token.trim() })
    }
  }
  return undefined
}

interface ReuseCoverage {
  readonly tomlPaths: ReadonlySet<string>
  readonly dep5: ReadonlySet<string>
  readonly incomplete: readonly string[]
}

/** A minimal REUSE reader: exact paths from REUSE.toml, globs from dep5. */
function readReuseCoverage(snapshot: LegalFileSnapshot): ReuseCoverage {
  const tomlPaths = new Set<string>()
  const incomplete: string[] = []
  for (const file of snapshot.files) {
    if (baseNameOf(file).toLowerCase() !== 'reuse.toml') continue
    const text = snapshot.readFile(file)
    if (text === undefined) continue
    incomplete.push(UI_TEXT.legalScanner.m055)
    for (const annotation of text.split('[[annotations]]').slice(1)) {
      const fields = parseTomlSection('[annotation]\n' + annotation, 'annotation')
      const paths = fields.get('path')
      const copyright = fields.get('SPDX-FileCopyrightText')
      const license = fields.get('SPDX-License-Identifier')
      if (
        copyright === undefined ||
        typeof license !== 'string' ||
        copyright.length === 0 ||
        !parseSpdxExpression(license).ok
      )
        continue
      const annotationPaths = typeof paths === 'string' ? [paths] : (paths ?? [])
      for (const path of annotationPaths) {
        if (!path.includes('*') && !path.includes('?')) tomlPaths.add(path)
      }
    }
  }
  const dep5 = new Set<string>()
  const dep5File = snapshot.files
    .filter((file) => file === '.reuse/dep5' || file.endsWith('/.reuse/dep5'))
    .toSorted((a, b) => compareLegalText(a, b))[0]
  if (dep5File !== undefined) {
    const text = snapshot.readFile(dep5File)
    if (text !== undefined) {
      let current = ''
      let hasCopyright = false
      let hasLicense = false
      const commit = (): void => {
        if (current !== '' && hasCopyright && hasLicense) {
          dep5.add(current)
        }
      }
      const listed4 = text.split('\n')
      for (const line of listed4) {
        const files = /^Files:\s*(.+?)\s*$/.exec(line)?.[1]
        if (files !== undefined) {
          commit()
          current = files
          hasCopyright = false
          hasLicense = false
          continue
        }
        if (/^Copyright:\s*\S/i.test(line)) hasCopyright = true
        const license = /^(?:License|SPDX-License-Identifier):\s*(.+)/i.exec(line)?.[1]
        if (license !== undefined && parseSpdxExpression(license).ok) hasLicense = true
      }
      commit()
    }
  }
  return { tomlPaths, dep5, incomplete }
}

function isDep5Covered(pattern: string, file: string): boolean {
  return isLegalGlobMatch(pattern, file)
}

/** Filename and explicit source-reference leads, never an ownership verdict. */
export function scanAttributionRisks(snapshot: LegalFileSnapshot): HeaderScanResult {
  const findings: LegalFindingDraft[] = []
  const reuse = readReuseCoverage(snapshot)
  const assetExtension =
    /\.(?:png|jpe?g|gif|webp|svg|ico|woff2?|ttf|otf|mp[34]|wav|pdf|safetensors|onnx)$/i
  const sourceReference =
    /(?:stackoverflow\.com\/(?:questions|a)\/|gist\.github\.com\/|(?:copied|adapted|taken)\s+from\s+https?:\/\/)/i
  for (const file of snapshot.files) {
    if (isGeneratedPath(file)) continue
    if (assetExtension.test(file)) {
      const sidecar = snapshot.files.includes(`${file}.license`)
        ? snapshot.readFile(`${file}.license`)
        : undefined
      const hasSidecar = hasSidecarProvenance(sidecar)
      if (
        hasSidecar ||
        reuse.tomlPaths.has(file) ||
        [...reuse.dep5].some((pattern) => isDep5Covered(pattern, file))
      )
        continue
      findings.push({
        severity: 'advice',
        category: 'distribution',
        file,
        evidenceSource: fill(UI_TEXT.legalScanner.m056, { v0: file }),
        confidence: 0.5,
        explanation: fill(UI_TEXT.legalScanner.m057, { v0: file }),
        recommendation: UI_TEXT.legalScanner.m058,
        fixable: false,
      })
    } else if (isSourceFile(file)) {
      const text = snapshot.readFile(file)
      if (text === undefined || hasBinaryContent(text)) continue
      const reference = topLines(text).find((line) => sourceReference.test(line))
      if (reference === undefined) continue
      findings.push({
        severity: 'advice',
        category: 'license',
        file,
        evidenceSource: fill(UI_TEXT.legalScanner.m059, { v0: file }),
        confidence: 0.5,
        explanation: fill(UI_TEXT.legalScanner.m060, { v0: file }),
        recommendation: UI_TEXT.legalScanner.m061,
        fixable: false,
        evidenceExcerpt: excerpt(reference),
      })
    }
  }
  return { findings, incomplete: reuse.incomplete, excluded: [] }
}

/**
 * Check headers over the snapshot's source files. `projectLicenses` holds
 * the canonical ids the project declares; an empty list skips the
 * file-against-project comparison instead of flagging every header.
 */
export function scanHeaders(
  snapshot: LegalFileSnapshot,
  policy: LegalHeaderPolicy,
  projectLicenses: readonly string[],
): HeaderScanResult {
  const findings: LegalFindingDraft[] = []
  const incomplete: string[] = []
  const excluded: string[] = []

  if (policy === 'off') {
    incomplete.push(UI_TEXT.legalScanner.m062)
    return { findings, incomplete, excluded }
  }

  const reuse = readReuseCoverage(snapshot)
  incomplete.push(...reuse.incomplete)
  const fileSet = new Set(snapshot.files)
  const projectSet = new Set(projectLicenses)

  const listed5 = snapshot.files
  for (const file of listed5) {
    if (!isSourceFile(file) || isLicenseFileName(baseNameOf(file))) {
      continue
    }
    const text = snapshot.readFile(file)
    if (text === undefined || hasBinaryContent(text)) {
      incomplete.push(fill(UI_TEXT.legalScanner.m063, { v0: file }))
      continue
    }
    let lines = topLines(text)
    if (isGeneratedPath(file) || lines.some((line) => GENERATED_MARKER.test(line))) {
      excluded.push(file)
      continue
    }
    if (
      reuse.tomlPaths.has(file) ||
      [...reuse.dep5].some((pattern) => isDep5Covered(pattern, file))
    ) {
      continue
    }

    const sidecar = fileSet.has(`${file}.license`)
      ? snapshot.readFile(`${file}.license`)
      : undefined
    const hasSidecar = hasSidecarProvenance(sidecar)
    if (hasSidecar) lines = topLines(sidecar)
    const { copyrightLine, spdxLine } = readHeader(lines)
    const isMissingCopyright = copyrightLine === undefined
    const isMissingSpdx = spdxLine === undefined
    if (isMissingCopyright || isMissingSpdx) {
      if (policy === 'required') {
        if (isMissingCopyright) {
          findings.push({
            severity: 'should-fix',
            category: 'copyrightHeader',
            file,
            line: 1,
            evidenceSource: fill(UI_TEXT.legalScanner.m064, { v0: file }),
            confidence: 0.8,
            explanation: fill(UI_TEXT.legalScanner.m065, { v0: file }),
            recommendation: UI_TEXT.legalScanner.m066,
            fixable: file
              .split('/')
              .every(
                (segment) =>
                  !['vendor', 'third_party', 'third-party', 'node_modules'].includes(segment),
              ),
          })
        }
        if (isMissingSpdx) {
          findings.push({
            severity: 'should-fix',
            category: 'spdxIdentifier',
            file,
            line: 1,
            evidenceSource: fill(UI_TEXT.legalScanner.m064, { v0: file }),
            confidence: 0.8,
            explanation: fill(UI_TEXT.legalScanner.m067, { v0: file }),
            recommendation: UI_TEXT.legalScanner.m068,
            fixable: file
              .split('/')
              .every(
                (segment) =>
                  !['vendor', 'third_party', 'third-party', 'node_modules'].includes(segment),
              ),
          })
        }
      } else {
        let missing = UI_TEXT.legalScanner.copyrightSpdxLines
        if (!isMissingCopyright) missing = UI_TEXT.legalScanner.spdxLine
        else if (!isMissingSpdx) missing = UI_TEXT.legalScanner.copyrightLine

        findings.push({
          severity: 'advice',
          category: 'codeQualityHeader',
          file,
          line: 1,
          evidenceSource: fill(UI_TEXT.legalScanner.m064, { v0: file }),
          confidence: 0.7,
          explanation: fill(UI_TEXT.legalScanner.m069, { v0: file, v1: missing }),
          recommendation: UI_TEXT.legalScanner.m070,
          fixable: file
            .split('/')
            .every(
              (segment) =>
                !['vendor', 'third_party', 'third-party', 'node_modules'].includes(segment),
            ),
        })
      }
    }

    for (const [index, line] of lines.entries()) {
      const entry = { ...readHeader([line]), index }
      const { holder } = entry
      const copyrightLine = entry.copyrightLine === undefined ? undefined : entry.index + 1
      if (holder !== undefined && copyrightLine !== undefined) {
        const problem = dateProblem(holder)
        if (problem !== undefined) {
          findings.push({
            severity: policy === 'required' ? 'should-fix' : 'advice',
            category: policy === 'required' ? 'copyrightHeader' : 'codeQualityHeader',
            file,
            line: copyrightLine,
            evidenceSource: fill(UI_TEXT.legalScanner.m064, { v0: file }),
            confidence: 0.85,
            explanation: fill(UI_TEXT.legalScanner.m071, { v0: file, v1: problem }),
            recommendation: UI_TEXT.legalScanner.m072,
            fixable: false,
            evidenceExcerpt: excerpt(lines[copyrightLine - 1] ?? ''),
          })
        }
      }

      const spdxRaw = entry.spdxRaw
      const spdxLine = entry.spdxLine === undefined ? undefined : entry.index + 1
      if (spdxRaw === undefined || spdxLine === undefined) continue

      const parsed = parseSpdxExpression(spdxRaw)
      if (!parsed.ok) {
        findings.push({
          severity: 'should-fix',
          category: 'spdxIdentifier',
          file,
          line: spdxLine,
          evidenceSource: fill(UI_TEXT.legalScanner.m064, { v0: file }),
          confidence: 0.9,
          explanation: fill(UI_TEXT.legalScanner.m073, { v0: file, v1: spdxRaw, v2: parsed.error }),
          recommendation: UI_TEXT.legalScanner.m074,
          fixable: false,
          evidenceExcerpt: excerpt(spdxRaw),
        })
        continue
      }
      const listed6 = parsed.licenses
      for (const license of listed6) {
        const canonical = license.canonicalId ?? (license.custom ? license.id : undefined)
        if (canonical === undefined || license.custom) {
          findings.push({
            severity: 'advice',
            category: 'spdxIdentifier',
            file,
            line: spdxLine,
            evidenceSource: fill(UI_TEXT.legalScanner.m064, { v0: file }),
            confidence: 0.7,
            explanation: fill(UI_TEXT.legalScanner.m025, { v0: file, v1: license.id }),
            recommendation: UI_TEXT.legalScanner.m075,
            fixable: false,
            evidenceExcerpt: excerpt(spdxRaw),
          })
        } else if (license.deprecated || license.plus) {
          findings.push({
            severity: 'advice',
            category: 'spdxIdentifier',
            file,
            line: spdxLine,
            evidenceSource: fill(UI_TEXT.legalScanner.m064, { v0: file }),
            confidence: 0.8,
            explanation: fill(UI_TEXT.legalScanner.m076, { v0: file, v1: license.id }),
            recommendation: UI_TEXT.legalScanner.m077,
            fixable: false,
            evidenceExcerpt: excerpt(spdxRaw),
          })
        } else if (license.exception !== undefined && !license.exception.known) {
          findings.push({
            severity: 'advice',
            category: 'spdxIdentifier',
            file,
            line: spdxLine,
            evidenceSource: fill(UI_TEXT.legalScanner.m064, { v0: file }),
            confidence: 0.7,
            explanation: fill(UI_TEXT.legalScanner.m029, { v0: file, v1: license.exception.id }),
            recommendation: UI_TEXT.legalScanner.m030,
            fixable: false,
            evidenceExcerpt: excerpt(spdxRaw),
          })
        }
      }
      const firstSpdx = readHeader(lines).spdxRaw
      if (firstSpdx !== undefined && firstSpdx !== spdxRaw) {
        findings.push({
          severity: 'should-fix',
          category: 'spdxIdentifier',
          file,
          line: spdxLine,
          evidenceSource: fill(UI_TEXT.legalScanner.m064, { v0: file }),
          confidence: 0.8,
          explanation: fill(UI_TEXT.legalScanner.m078, { v0: file, v1: firstSpdx, v2: spdxRaw }),
          recommendation: UI_TEXT.legalScanner.m079,
          fixable: false,
          evidenceExcerpt: excerpt(spdxRaw),
        })
      }
      if (projectSet.size === 0) continue
      {
        const isCovered = orAlternatives(parsed.root).some((branch) =>
          branch.every((id) => projectSet.has(id)),
        )
        if (!isCovered) {
          findings.push({
            severity: 'should-fix',
            category: 'spdxIdentifier',
            file,
            line: spdxLine,
            evidenceSource: fill(UI_TEXT.legalScanner.m064, { v0: file }),
            confidence: 0.8,
            explanation: fill(UI_TEXT.legalScanner.m080, {
              v0: file,
              v1: spdxRaw,
              v2: [...projectSet].toSorted((a, b) => compareLegalText(a, b)).join(', '),
            }),
            recommendation: UI_TEXT.legalScanner.m081,
            fixable: false,
            evidenceExcerpt: excerpt(spdxRaw),
          })
        }
      }
    }
  }

  return { findings, incomplete, excluded }
}
