import { compareLegalText } from './files'
// Copyright headers and SPDX identifiers (M97, PLAN.md D76): per source
// file, under the header-policy setting. Shebangs, byte-order marks and
// editor mode lines are tolerated; generated files, REUSE declarations and
// license sidecars are honored, and the report names the generated
// exclusion. An earlier year alone is never stale; conflicting dates are.

import type { LegalHeaderPolicy } from '../../shared/constants'
import type { LegalFindingDraft } from './finding'
import type { LegalFileSnapshot } from './files'
import {
  baseNameOf,
  hasBinaryContent,
  excerpt,
  isLicenseFileName,
  topLines,
  isLegalGlobMatch,
} from './files'
import { orAlternatives, parseSpdxExpression } from './spdx'
import { parseTomlSection } from './ecosystems/toml'

/** What the header reader established, including named exclusions. */
export interface HeaderScanResult {
  readonly findings: readonly LegalFindingDraft[]
  readonly incomplete: readonly string[]
  /** Generated files excluded from header checks, for the report. */
  readonly excluded: readonly string[]
}

/** Source extensions whose top lines may carry a copyright header. */
const SOURCE_EXTENSIONS: ReadonlySet<string> = new Set([
  'ts',
  'tsx',
  'mts',
  'cts',
  'js',
  'jsx',
  'mjs',
  'cjs',
  'py',
  'pyi',
  'rb',
  'php',
  'cs',
  'java',
  'kt',
  'kts',
  'scala',
  'go',
  'rs',
  'c',
  'h',
  'cc',
  'cpp',
  'cxx',
  'hpp',
  'hh',
  'm',
  'mm',
  'swift',
  'sh',
  'bash',
  'ps1',
  'css',
  'scss',
  'less',
  'html',
  'vue',
  'svelte',
  'sql',
  'lua',
  'pl',
  'pm',
  'r',
  'jl',
  'ex',
  'exs',
  'erl',
])

/** Path segments and suffixes that mark generated output, not authorship. */
const GENERATED_SEGMENTS: ReadonlySet<string> = new Set([
  'dist',
  'build',
  'out',
  'coverage',
  'target',
  'bin',
  'obj',
  'gen',
  'generated',
  'node_modules',
  '.git',
])
const GENERATED_SUFFIXES = ['.min.js', '.bundle.js', '.chunk.js', '.gen.ts', '.g.ts']
const GENERATED_MARKER = /@generated|auto-generated|do not edit|do not modify|generated by/i

const COPYRIGHT_LINE =
  /^\s*(?:(?:\/\/|#|\/\*+|\*|<!--|--|;)\s*)?(?:copyright\s*(?:©|\(c\))?|SPDX-FileCopyrightText:)\s*(.+)/i
const YEAR_TOKEN = /\d{4}(?:\s*(?:-|–)\s*\d{2,4})?/g
const FOUR_DIGIT_YEAR = /^\d{4}$/
const YEAR_RANGE_SPLIT = /-|–/
const SPDX_LINE = /^\s*(?:(?:\/\/|#|\/\*+|\*|<!--|--|;)\s*)?SPDX-License-Identifier:\s*(.+?)\s*$/i
const COMMENT_TRAILER = /\s*(?:\*\/|-->)\s*$/

function isGeneratedPath(file: string): boolean {
  return (
    GENERATED_SUFFIXES.some((suffix) => file.endsWith(suffix)) ||
    file.split('/').some((segment) => GENERATED_SEGMENTS.has(segment.toLowerCase()))
  )
}

function isSourceFile(file: string): boolean {
  const base = baseNameOf(file)
  const dot = base.lastIndexOf('.')
  return dot !== -1 && SOURCE_EXTENSIONS.has(base.slice(dot + 1).toLowerCase())
}

interface HeaderEvidence {
  readonly copyrightLine: number | undefined
  readonly holder: string | undefined
  readonly spdxLine: number | undefined
  readonly spdxRaw: string | undefined
}

function readHeader(lines: string[]): HeaderEvidence {
  let copyrightLine: number | undefined
  let holder: string | undefined
  let spdxLine: number | undefined
  let spdxRaw: string | undefined
  const listed1 = lines.entries()
  for (const [index, line] of listed1) {
    if (copyrightLine === undefined) {
      const copyright = COPYRIGHT_LINE.exec(line)
      if (copyright?.[1] !== undefined) {
        copyrightLine = index + 1
        holder = copyright[1].replace(COMMENT_TRAILER, '').trim()
      }
    }
    if (spdxLine !== undefined) continue

    const spdx = SPDX_LINE.exec(line)
    if (spdx?.[1] === undefined) {
      continue
    }

    spdxLine = index + 1
    spdxRaw = spdx[1]
      .replace(COMMENT_TRAILER, '')
      .replace(/[,;*#]+$/, '')
      .trim()
  }
  return { copyrightLine, holder, spdxLine, spdxRaw }
}

function expandEndYear(start: number, end: number): number {
  if (end >= 100) {
    return end
  }
  const century = Math.floor(start / 100) * 100
  const expanded = century + end
  return expanded < start ? expanded + 100 : expanded
}

/** Conflicting or impossible dates in a holder string, as one sentence. */
function dateProblem(holder: string): string | undefined {
  const tokens = holder.match(YEAR_TOKEN) ?? []
  for (const token of tokens) {
    const parts = token.split(YEAR_RANGE_SPLIT).map((part) => part.trim())
    const first = parts[0] ?? ''
    if (!FOUR_DIGIT_YEAR.test(first)) {
      return `the year ${first} is not a four-digit year`
    }
    const start = Number(first)
    if (start < 100) {
      return `the year ${first} is impossible`
    }
    const second = parts[1] ?? ''
    if (second !== '' && expandEndYear(start, Number(second)) < start) {
      return `the range ${token.trim()} ends before it starts`
    }
  }
  return undefined
}

interface ReuseCoverage {
  readonly tomlPaths: ReadonlySet<string>
  readonly dep5: ReadonlySet<string>
  readonly incomplete: readonly string[]
}

/** A minimal REUSE reader: exact paths from REUSE.toml, globs from dep5. */
function readReuseCoverage(snapshot: LegalFileSnapshot): ReuseCoverage {
  const tomlPaths = new Set<string>()
  const incomplete: string[] = []
  for (const file of snapshot.files) {
    if (baseNameOf(file).toLowerCase() !== 'reuse.toml') continue
    const text = snapshot.readFile(file)
    if (text === undefined) continue
    incomplete.push(
      'not checked: complex REUSE patterns, precedence and ownership relationships; only complete exact-path annotations are honored',
    )
    for (const annotation of text.split('[[annotations]]').slice(1)) {
      const fields = parseTomlSection('[annotation]\n' + annotation, 'annotation')
      const paths = fields.get('path')
      const copyright = fields.get('SPDX-FileCopyrightText')
      const license = fields.get('SPDX-License-Identifier')
      if (
        copyright === undefined ||
        typeof license !== 'string' ||
        copyright.length === 0 ||
        !parseSpdxExpression(license).ok
      )
        continue
      const annotationPaths = typeof paths === 'string' ? [paths] : (paths ?? [])
      for (const path of annotationPaths) {
        if (!path.includes('*') && !path.includes('?')) tomlPaths.add(path)
      }
    }
  }
  const dep5 = new Set<string>()
  const dep5File = snapshot.files
    .filter((file) => file === '.reuse/dep5' || file.endsWith('/.reuse/dep5'))
    .toSorted((a, b) => compareLegalText(a, b))[0]
  if (dep5File !== undefined) {
    const text = snapshot.readFile(dep5File)
    if (text !== undefined) {
      let current = ''
      let hasCopyright = false
      let hasLicense = false
      const commit = (): void => {
        if (current !== '' && hasCopyright && hasLicense) {
          dep5.add(current)
        }
      }
      const listed4 = text.split('\n')
      for (const line of listed4) {
        const files = /^Files:\s*(.+?)\s*$/.exec(line)?.[1]
        if (files !== undefined) {
          commit()
          current = files
          hasCopyright = false
          hasLicense = false
          continue
        }
        if (/^Copyright:\s*\S/i.test(line)) hasCopyright = true
        const license = /^(?:License|SPDX-License-Identifier):\s*(.+)/i.exec(line)?.[1]
        if (license !== undefined && parseSpdxExpression(license).ok) hasLicense = true
      }
      commit()
    }
  }
  return { tomlPaths, dep5, incomplete }
}

function isDep5Covered(pattern: string, file: string): boolean {
  return isLegalGlobMatch(pattern, file)
}

/** Filename and explicit source-reference leads, never an ownership verdict. */
export function scanAttributionRisks(snapshot: LegalFileSnapshot): HeaderScanResult {
  const findings: LegalFindingDraft[] = []
  const reuse = readReuseCoverage(snapshot)
  const assetExtension =
    /\.(?:png|jpe?g|gif|webp|svg|ico|woff2?|ttf|otf|mp[34]|wav|pdf|safetensors|onnx)$/i
  const sourceReference =
    /(?:stackoverflow\.com\/(?:questions|a)\/|gist\.github\.com\/|(?:copied|adapted|taken)\s+from\s+https?:\/\/)/i
  for (const file of snapshot.files) {
    if (isGeneratedPath(file)) continue
    if (assetExtension.test(file)) {
      const sidecar = snapshot.files.includes(`${file}.license`)
        ? snapshot.readFile(`${file}.license`)
        : undefined
      const hasSidecar =
        sidecar !== undefined &&
        /SPDX-FileCopyrightText:\s*\S/.test(sidecar) &&
        /SPDX-License-Identifier:\s*\S/.test(sidecar)
      if (
        hasSidecar ||
        reuse.tomlPaths.has(file) ||
        [...reuse.dep5].some((pattern) => isDep5Covered(pattern, file))
      )
        continue
      findings.push({
        severity: 'advice',
        category: 'distribution',
        file,
        evidenceSource: `asset inventory at ${file}`,
        confidence: 0.5,
        explanation: `${file} has no observed per-file provenance declaration; its filename alone cannot establish ownership or distribution rights.`,
        recommendation:
          'Record the asset source, author and applicable terms from verified ownership in a sidecar or REUSE declaration.',
        fixable: false,
      })
    } else if (isSourceFile(file)) {
      const text = snapshot.readFile(file)
      if (text === undefined || hasBinaryContent(text)) continue
      const reference = topLines(text).find((line) => sourceReference.test(line))
      if (reference === undefined) continue
      findings.push({
        severity: 'advice',
        category: 'license',
        file,
        evidenceSource: `source reference at ${file}`,
        confidence: 0.5,
        explanation: `${file} contains a source reference whose provenance and applicable terms need review; a reference alone does not prove copying or infringement.`,
        recommendation:
          'Verify the original source, author, date, license and attribution for any copied material; keep legitimate upstream headers.',
        fixable: false,
        evidenceExcerpt: excerpt(reference),
      })
    }
  }
  return { findings, incomplete: reuse.incomplete, excluded: [] }
}

/**
 * Check headers over the snapshot's source files. `projectLicenses` holds
 * the canonical ids the project declares; an empty list skips the
 * file-against-project comparison instead of flagging every header.
 */
export function scanHeaders(
  snapshot: LegalFileSnapshot,
  policy: LegalHeaderPolicy,
  projectLicenses: readonly string[],
): HeaderScanResult {
  const findings: LegalFindingDraft[] = []
  const incomplete: string[] = []
  const excluded: string[] = []

  if (policy === 'off') {
    incomplete.push('not checked: copyright header checks are off by policy')
    return { findings, incomplete, excluded }
  }

  const reuse = readReuseCoverage(snapshot)
  incomplete.push(...reuse.incomplete)
  const fileSet = new Set(snapshot.files)
  const projectSet = new Set(projectLicenses)

  const listed5 = snapshot.files
  for (const file of listed5) {
    if (!isSourceFile(file) || isLicenseFileName(baseNameOf(file))) {
      continue
    }
    const text = snapshot.readFile(file)
    if (text === undefined || hasBinaryContent(text)) {
      incomplete.push(`not checked: ${file} is unreadable or binary header material`)
      continue
    }
    let lines = topLines(text)
    if (isGeneratedPath(file) || lines.some((line) => GENERATED_MARKER.test(line))) {
      excluded.push(file)
      continue
    }
    if (
      reuse.tomlPaths.has(file) ||
      [...reuse.dep5].some((pattern) => isDep5Covered(pattern, file))
    ) {
      continue
    }

    const sidecar = fileSet.has(`${file}.license`)
      ? snapshot.readFile(`${file}.license`)
      : undefined
    const hasSidecar =
      sidecar !== undefined &&
      /SPDX-FileCopyrightText:\s*\S/.test(sidecar) &&
      /SPDX-License-Identifier:\s*\S/.test(sidecar)
    if (hasSidecar) lines = topLines(sidecar)
    const { copyrightLine, holder, spdxLine, spdxRaw } = readHeader(lines)
    const isMissingCopyright = copyrightLine === undefined
    const isMissingSpdx = spdxLine === undefined
    if (isMissingCopyright || isMissingSpdx) {
      if (policy === 'required') {
        if (isMissingCopyright) {
          findings.push({
            severity: 'should-fix',
            category: 'copyrightHeader',
            file,
            line: 1,
            evidenceSource: `header reader at ${file}`,
            confidence: 0.8,
            explanation: `${file} has no copyright line in its first lines, but the header policy requires one.`,
            recommendation:
              'Add the project copyright line from verified ownership; never replace a third-party header.',
            fixable: file
              .split('/')
              .every(
                (segment) =>
                  !['vendor', 'third_party', 'third-party', 'node_modules'].includes(segment),
              ),
          })
        }
        if (isMissingSpdx) {
          findings.push({
            severity: 'should-fix',
            category: 'spdxIdentifier',
            file,
            line: 1,
            evidenceSource: `header reader at ${file}`,
            confidence: 0.8,
            explanation: `${file} has no SPDX-License-Identifier line, but the header policy requires one.`,
            recommendation: 'Add the SPDX identifier matching the applicable license.',
            fixable: file
              .split('/')
              .every(
                (segment) =>
                  !['vendor', 'third_party', 'third-party', 'node_modules'].includes(segment),
              ),
          })
        }
      } else {
        let missing = 'copyright or SPDX-License-Identifier lines'
        if (!isMissingCopyright) missing = 'an SPDX-License-Identifier line'
        else if (!isMissingSpdx) missing = 'a copyright line'

        findings.push({
          severity: 'advice',
          category: 'codeQualityHeader',
          file,
          line: 1,
          evidenceSource: `header reader at ${file}`,
          confidence: 0.7,
          explanation: `${file} has no ${missing} in its first lines.`,
          recommendation:
            'Add the project copyright header for hygiene; the policy leaves it optional.',
          fixable: file
            .split('/')
            .every(
              (segment) =>
                !['vendor', 'third_party', 'third-party', 'node_modules'].includes(segment),
            ),
        })
      }
    }

    if (holder !== undefined && copyrightLine !== undefined) {
      const problem = dateProblem(holder)
      if (problem !== undefined) {
        findings.push({
          severity: policy === 'required' ? 'should-fix' : 'advice',
          category: policy === 'required' ? 'copyrightHeader' : 'codeQualityHeader',
          file,
          line: copyrightLine,
          evidenceSource: `header reader at ${file}`,
          confidence: 0.85,
          explanation: `${file} has a copyright line, but ${problem}.`,
          recommendation: 'Correct the date with the holder; an earlier year alone is never stale.',
          fixable: false,
          evidenceExcerpt: excerpt(lines[copyrightLine - 1] ?? ''),
        })
      }
    }

    if (spdxRaw === undefined || spdxLine === undefined) continue

    const parsed = parseSpdxExpression(spdxRaw)
    if (!parsed.ok) {
      findings.push({
        severity: 'should-fix',
        category: 'spdxIdentifier',
        file,
        line: spdxLine,
        evidenceSource: `header reader at ${file}`,
        confidence: 0.9,
        explanation: `${file} declares SPDX-License-Identifier ${spdxRaw}, which does not parse: ${parsed.error}.`,
        recommendation:
          'Write the identifier as an SPDX expression (AND, OR and WITH in uppercase).',
        fixable: false,
        evidenceExcerpt: excerpt(spdxRaw),
      })
      continue
    }
    const listed6 = parsed.licenses
    for (const license of listed6) {
      const canonical = license.canonicalId ?? (license.custom ? license.id : undefined)
      if (canonical === undefined || license.custom) {
        findings.push({
          severity: 'advice',
          category: 'spdxIdentifier',
          file,
          line: spdxLine,
          evidenceSource: `header reader at ${file}`,
          confidence: 0.7,
          explanation: `${file} declares the custom reference ${license.id}: its terms need a human read.`,
          recommendation: 'Confirm the referenced text exists beside the file or in REUSE.toml.',
          fixable: false,
          evidenceExcerpt: excerpt(spdxRaw),
        })
      } else if (license.deprecated || license.plus) {
        findings.push({
          severity: 'advice',
          category: 'spdxIdentifier',
          file,
          line: spdxLine,
          evidenceSource: `header reader at ${file}`,
          confidence: 0.8,
          explanation: `${file} declares ${license.id}, a deprecated SPDX identifier form.`,
          recommendation: 'Use the current identifier from the SPDX License List.',
          fixable: false,
          evidenceExcerpt: excerpt(spdxRaw),
        })
      } else if (license.exception !== undefined && !license.exception.known) {
        findings.push({
          severity: 'advice',
          category: 'spdxIdentifier',
          file,
          line: spdxLine,
          evidenceSource: `header reader at ${file}`,
          confidence: 0.7,
          explanation: `${file} declares the exception ${license.exception.id}, which is not on the SPDX exception list.`,
          recommendation: 'Confirm the exception text; an exception changes the analysis.',
          fixable: false,
          evidenceExcerpt: excerpt(spdxRaw),
        })
      }
    }
    if (projectSet.size === 0) continue
    {
      const isCovered = orAlternatives(parsed.root).some((branch) =>
        branch.every((id) => projectSet.has(id)),
      )
      if (!isCovered) {
        findings.push({
          severity: 'should-fix',
          category: 'spdxIdentifier',
          file,
          line: spdxLine,
          evidenceSource: `header reader at ${file}`,
          confidence: 0.8,
          explanation: `${file} declares ${spdxRaw}, outside the project licenses ${[...projectSet].toSorted((a, b) => compareLegalText(a, b)).join(', ')}.`,
          recommendation:
            'Confirm the file carries third-party terms (keep its header) or correct the identifier.',
          fixable: false,
          evidenceExcerpt: excerpt(spdxRaw),
        })
      }
    }
  }

  return { findings, incomplete, excluded }
}
