// M97 lane S: copyright headers and SPDX identifiers per source file.
// Shebangs, byte-order marks and mode lines are tolerated; generated
// files and REUSE declarations are honored; policy decides whether a
// missing header is a should-fix, hygiene advice or out of scope.

import { describe, expect, it } from 'vitest'
import { scanHeaders } from '../../src/core/legal/headers'
import { snapshotFrom } from './legal/helpers'

const headed = `// Copyright (c) 2026 Example Corp
// SPDX-License-Identifier: MIT
export const value = 1
`

describe('scanHeaders', () => {
  it('stays silent for a headed file under any active policy', () => {
    for (const policy of ['required', 'optional'] as const) {
      const result = scanHeaders(snapshotFrom({ 'src/ok.ts': headed }), policy, ['MIT'])
      expect(result.findings).toEqual([])
      expect(result.excluded).toEqual([])
    }
  })

  it('requires both lines under the required policy', () => {
    const result = scanHeaders(snapshotFrom({ 'src/bare.ts': 'export const value = 1\n' }), 'required', ['MIT'])
    expect(result.findings).toHaveLength(2)
    expect(result.findings.map((finding) => finding.category).toSorted()).toEqual([
      'copyrightHeader',
      'spdxIdentifier',
    ])
    expect(result.findings.every((finding) => finding.severity === 'should-fix')).toBe(true)
    expect(result.findings.every((finding) => finding.fixable)).toBe(true)
  })

  it('reports one hygiene note under the optional policy', () => {
    const result = scanHeaders(snapshotFrom({ 'src/bare.ts': 'export const value = 1\n' }), 'optional', ['MIT'])
    expect(result.findings).toHaveLength(1)
    expect(result.findings[0]?.category).toBe('codeQualityHeader')
    expect(result.findings[0]?.severity).toBe('advice')
  })

  it('skips checks under the off policy with an incomplete marker', () => {
    const result = scanHeaders(snapshotFrom({ 'src/bare.ts': 'export const value = 1\n' }), 'off', ['MIT'])
    expect(result.findings).toEqual([])
    expect(result.incomplete).toEqual(['not checked: copyright header checks are off by policy'])
  })

  it('tolerates shebangs, byte-order marks and mode lines', () => {
    const python = `#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Copyright (c) 2026 Example Corp
# SPDX-License-Identifier: MIT
value = 1
`
    const bom = '﻿// Copyright (c) 2026 Example Corp\n// SPDX-License-Identifier: MIT\n'
    const result = scanHeaders(
      snapshotFrom({ 'src/tool.py': python, 'src/bom.ts': bom }),
      'required',
      ['MIT'],
    )
    expect(result.findings).toEqual([])
  })

  it('flags a header identifier outside the project licenses', () => {
    const result = scanHeaders(
      snapshotFrom({ 'src/foreign.ts': '// Copyright (c) 2026 Other\n// SPDX-License-Identifier: Apache-2.0\n' }),
      'required',
      ['MIT'],
    )
    const mismatch = result.findings.find((finding) => finding.explanation.includes('outside the project'))
    expect(mismatch?.severity).toBe('should-fix')
    expect(mismatch?.fixable).toBe(false)
  })

  it('accepts a dual-licensed header with a matching branch', () => {
    const result = scanHeaders(
      snapshotFrom({
        'src/dual.ts': '// Copyright (c) 2026 Example\n// SPDX-License-Identifier: MIT OR GPL-3.0-only\n',
      }),
      'required',
      ['MIT'],
    )
    expect(result.findings).toEqual([])
  })

  it('flags malformed header identifiers', () => {
    const result = scanHeaders(
      snapshotFrom({ 'src/broken.ts': '// Copyright (c) 2026 Example\n// SPDX-License-Identifier: MIT or\n' }),
      'required',
      ['MIT'],
    )
    expect(result.findings).toHaveLength(1)
    expect(result.findings[0]?.explanation).toContain('does not parse')
  })

  it('flags custom, deprecated and unknown header terms as advice', () => {
    const result = scanHeaders(
      snapshotFrom({
        'src/custom.ts': '// Copyright (c) 2026 Example\n// SPDX-License-Identifier: LicenseRef-Mine\n',
        'src/old.ts': '// Copyright (c) 2026 Example\n// SPDX-License-Identifier: GPL-2.0\n',
      }),
      'optional',
      [],
    )
    expect(result.findings).toHaveLength(2)
    expect(result.findings.every((finding) => finding.severity === 'advice')).toBe(true)
  })

  it('flags conflicting dates but never a legitimate old year', () => {
    const result = scanHeaders(
      snapshotFrom({
        'src/old.ts': '// Copyright (c) 1998 Example\n// SPDX-License-Identifier: MIT\n',
        'src/odd.ts': '// Copyright (c) 2026-2020 Example\n// SPDX-License-Identifier: MIT\n',
      }),
      'required',
      ['MIT'],
    )
    expect(result.findings).toHaveLength(1)
    expect(result.findings[0]?.file).toBe('src/odd.ts')
    expect(result.findings[0]?.explanation).toContain('ends before it starts')
  })

  it('excludes generated files and names the exclusion', () => {
    const result = scanHeaders(
      snapshotFrom({
        'dist/bundle.js': 'export const value = 1\n',
        'src/gen.ts': '// @generated by protoc\nexport const value = 1\n',
      }),
      'required',
      ['MIT'],
    )
    expect(result.findings).toEqual([])
    expect(result.excluded.toSorted()).toEqual(['dist/bundle.js', 'src/gen.ts'])
  })

  it('honors REUSE.toml, sidecars and dep5 coverage', () => {
    const result = scanHeaders(
      snapshotFrom({
        'REUSE.toml': '[[annotations]]\npath = "src/toml.ts"\nSPDX-License-Identifier = "MIT"\n',
        'src/toml.ts': 'export const value = 1\n',
        'src/sidecar.ts': 'export const value = 1\n',
        'src/sidecar.ts.license': 'SPDX-License-Identifier: MIT\n',
        '.reuse/dep5': 'Files: src/dep5/*\nCopyright: 2026 Example\nSPDX-License-Identifier: MIT\n',
        'src/dep5/covered.ts': 'export const value = 1\n',
      }),
      'required',
      ['MIT'],
    )
    expect(result.findings).toEqual([])
  })

  it('skips binary files and non-source extensions', () => {
    const binary = `wOF2${String.fromCharCode(0)}Copyright 2026 inside binary`
    const result = scanHeaders(
      snapshotFrom({
        'src/blob.ts': binary,
        'src/font.woff2': 'wOF2 with a Copyright 2026 notice inside binary',
        'package.json': JSON.stringify({ name: 'example' }),
      }),
      'required',
      ['MIT'],
    )
    expect(result.findings).toEqual([])
  })

  it('misses headers past the line window instead of matching code', () => {
    const lines = Array.from({ length: 30 }, (_, index) => `const v${index} = ${index}`).join('\n')
    const result = scanHeaders(
      snapshotFrom({ 'src/late.ts': `${lines}\n// Copyright (c) 2026 Example\n` }),
      'required',
      ['MIT'],
    )
    expect(result.findings.length).toBeGreaterThan(0)
  })
})
