import { describe, expect, it } from 'vitest'
import { rulesFileTemplate } from '../../src/core/context/rulesTemplate'

describe('rulesFileTemplate', () => {
  it('follows the muse init layout with the project name and no detection claims', () => {
    expect(rulesFileTemplate('demo').split('\n')).toEqual([
      '# AGENTS.md',
      '',
      'Muse Code reads this file as project rules when it runs in this directory.',
      '',
      '## Project',
      '',
      '- Name: demo',
      '- Generated by Muse Spark Code (`muse init` writes the same layout).',
      '',
      '## Common Commands',
      '',
      '- List the build, test and lint commands here.',
      '',
      '## Project Layout',
      '',
      '- Describe the source, test and docs directories here.',
      '',
    ])
  })
})
