// The generator's build entry: its imports are visible to the dead-code gate.
export { featureCatalog, COMMAND_REFERENCE, referenceDescription } from '../featureCatalog'
export { COMMAND_IDS } from '../constants'
export { buildPalette } from '../palette'
export { slashCommandsOf } from '../slashCommands'
export { cliCommands } from '../cliCommands'
export { EN } from '../l10n/en'
export { permissionModeDetail } from '../permissionModes'
export { referenceText } from './text'
export { fill } from '../l10n/text'
export {
  ACP_AGENT_NAME,
  PAID_FEATURE_SETTINGS,
  PAID_FEATURES,
  MUSE_CODE_PAID_FEATURES,
  ACP_PAID_FEATURES,
  ACP_PAID_FLAGS,
  SETTING_DEFAULTS,
  DEFAULT_EFFORT,
  MODEL_EFFORT_LEVELS,
  THINKING_OFF_EFFORT,
  MODEL_API_EFFORT_OFF,
  MAX_IMAGE_BYTES,
  MAX_DOCUMENT_BYTES,
  MAX_TEXT_ATTACHMENT_BYTES,
  MAX_ATTACHMENTS_PER_MESSAGE,
  MAX_ENCODED_MEDIA_CHARS,
  MODEL_API_MEDIA_PER_REQUEST,
  MODEL_API_PDF_PAGE_IMAGES,
  EXEC_MODES,
  EXEC_OUTPUTS,
  EXEC_DEFAULT_MODE,
  EXEC_DEFAULT_OUTPUT,
  EXEC_DEFAULT_MAX_REQUESTS,
  EXEC_DEFAULT_TIMEOUT_SECONDS,
  EXEC_MAX_BUDGET_USD,
  EXEC_MAX_REQUESTS,
  EXEC_MIN_TIMEOUT_SECONDS,
  EXEC_MAX_TIMEOUT_SECONDS,
  ACP_BACKENDS,
  ACP_DEFAULT_BACKEND,
  ACP_CONFIG_IDS,
  PERMISSION_MODES,
  RULES_FILE_NAMES,
  SKILL_FILE_NAME,
  MEMORY_DIR_SEGMENTS,
  SHELL_SANDBOX_MODES,
  EFFORT_LEVELS,
  AGENT_FILE_NAME,
  PROJECT_AGENTS_DIR_SEGMENTS,
  PERSONAL_AGENTS_DIR_SEGMENTS,
  BROWSER_CHECK_MAX_ACTIONS,
} from '../constants'
export { parseGoalPrompt } from '../goalCommand'
export { parseReviewPrompt } from '../reviewCommand'
export { parseHandoffPrompt } from '../handoff'

// Reviewed host capability inventory: pairs are explicit, never a Cartesian claim.
// The tooling gate also checks tool/action coverage and host admission witnesses.
const capabilityPairs: readonly (readonly [string, readonly string[]])[] = [
  ['custom-agents', ['vscode:modelApi']],
  ['mcp-elicitation', ['vscode:modelApi']],
  ...[
    'best-of-n',
    'verify',
    'repo-map',
    'checkpoints',
    'rules',
    'schedules',
    'subagents',
    'auto',
    'hook-models',
    'cache',
    'budget',
    'judge',
  ].map((id): [string, readonly string[]] => [id, ['vscode:modelApi']]),
  ...[
    'auto-subscription',
    'native-agents',
    'native-search-cron',
    'voice',
    'judge-subscription',
  ].map((id): [string, readonly string[]] => [id, ['vscode:museCode']]),
  ...[
    'attachments',
    'effort',
    'conversation-actions',
    'code-output',
    'code-intelligence',
    'shell',
    'session-board',
    'edit-review',
    'free-dictation',
    'chat',
    'account',
    'permissions',
    'history',
    'context',
    'skills',
    'imports',
    'memory',
    'mcp',
    'hooks',
    'git',
    'tasks',
    'exports',
    'review',
    'plans',
    'goals',
    'handoff',
    'browser',
    'tab',
    'support',
  ].map((id): [string, readonly string[]] => [id, ['vscode:museCode', 'vscode:modelApi']]),
  ...['acp'].map((id): [string, readonly string[]] => [id, ['acp:museCode', 'acp:modelApi']]),
  // M112: ACP asks through forms or text and answers with /questions and /answer.
  ['questions', ['vscode:museCode', 'vscode:modelApi', 'acp:museCode', 'acp:modelApi']],
  // M109: the vault panel and lock in VS Code, /vault and permission mapping
  // in ACP, on either backend; values never reach either surface.
  ['vault', ['vscode:museCode', 'vscode:modelApi', 'acp:museCode', 'acp:modelApi']],
  ...['web-fetch', 'images'].map((id): [string, readonly string[]] => [
    id,
    ['vscode:museCode', 'vscode:modelApi', 'acp:modelApi'],
  ]),
  ...['search'].map((id): [string, readonly string[]] => [id, ['vscode:modelApi', 'acp:modelApi']]),
]
export const REFERENCE_CAPABILITIES = Object.fromEntries<readonly string[]>(capabilityPairs)
export const REFERENCE_FEATURE_IDS = Object.keys(REFERENCE_CAPABILITIES)
export { referenceKeyboardActions, WEBVIEW_KEYBINDINGS, webviewKey } from '../keybindings'
export const REFERENCE_ACTION_FEATURES = {
  openSettings: 'support',
  openKeybindings: 'support',
  openLog: 'support',
  toggleFocusView: 'chat',
  toggleCtrlEnterToSend: 'chat',
  hideOnboarding: 'chat',
  reload: 'support',
  openMuseSettings: 'chat',
  manageSkills: 'skills',
  importSkills: 'skills',
  importFromAgents: 'imports',
  showMcpServers: 'mcp',
  showHooks: 'hooks',
  showMemory: 'memory',
  newWorktree: 'git',
  removeWorktree: 'git',
  openPullRequestInConversation: 'git',
  restartMuseCode: 'chat',
  openTasksTab: 'chat',
  installBundledSkills: 'skills',
  updateBundledSkills: 'skills',
  declineBundledSkills: 'skills',
  showWhatsNew: 'chat',

  readReference: 'support',
  openReferenceSetting: 'support',
  runReferenceCommand: 'support',
  ready: 'chat',
  inputFocusChanged: 'chat',
  surfaceFocused: 'chat',
  webviewError: 'chat',
  sendMessage: 'chat',
  withdrawQueued: 'chat',
  runManualHook: 'hooks',
  cancelTurn: 'chat',
  signIn: 'account',
  installMuseCode: 'account',
  cancelSignIn: 'account',
  signOut: 'chat',
  retryBackend: 'chat',
  openExternal: 'chat',
  setModel: 'chat',
  setEffort: 'chat',
  setThinking: 'chat',
  setPermissionMode: 'chat',
  clearConversation: 'conversation-actions',
  compact: 'chat',
  requestHandoff: 'chat',
  confirmHandoff: 'chat',
  cancelHandoff: 'chat',
  goalCommand: 'goals',
  scheduleCreate: 'schedules',
  scheduleList: 'schedules',
  scheduleCancel: 'schedules',
  scheduleRun: 'schedules',
  exportConversation: 'conversation-actions',
  importSession: 'conversation-actions',
  openShareFile: 'exports',
  listSkills: 'skills',
  searchMentions: 'chat',
  pickFile: 'chat',
  pickMentionFile: 'chat',
  attachImageData: 'attachments',
  removeAttachment: 'attachments',
  droppedUris: 'chat',
  hostAction: 'chat',
  decideApproval: 'chat',
  cancelQuestion: 'questions',
  elicitationAnswer: 'mcp-elicitation',
  answerQuestion: 'questions',
  clarifyQuestion: 'questions',
  moveToBackground: 'chat',
  stopTask: 'chat',
  stopAllTasks: 'chat',
  runUserShell: 'chat',
  readOutput: 'code-output',
  readToolImage: 'chat',
  openOutput: 'code-output',
  copyText: 'chat',
  insertCode: 'code-output',
  applyCode: 'code-output',
  openEditDiff: 'chat',
  revertEdit: 'chat',
  openFile: 'chat',
  rewindCode: 'conversation-actions',
  startReview: 'review',
  readReviewChanges: 'review',
  revertReviewHunk: 'review',
  restoreFiles: 'chat',
  redoRestore: 'chat',
  listSessions: 'conversation-actions',
  requestSessionBoard: 'conversation-actions',
  activateBoardSession: 'conversation-actions',
  startBestOfN: 'best-of-n',
  takeBestOfNAttempt: 'best-of-n',
  openBestOfNAttempt: 'best-of-n',
  cancelBestOfN: 'best-of-n',
  readChildSession: 'conversation-actions',
  subagentControl: 'native-agents',
  subagentMessage: 'native-agents',
  resumeSession: 'conversation-actions',
  setSessionArchived: 'conversation-actions',
  forkSession: 'conversation-actions',
  openSideChat: 'chat',
  savePlan: 'plans',
  implementPlan: 'plans',
  showPlans: 'plans',
  renameSession: 'conversation-actions',
  readUsage: 'chat',
  dictation: 'chat',
  setPaidFeature: 'budget',
  forgetPaidUse: 'budget',
  gitAction: 'git',
  gitCommit: 'git',
  gitCreatePullRequest: 'git',
  openReport: 'chat',
  updateReport: 'chat',
  exportReport: 'chat',
  reportWebviewError: 'chat',
}
export { HOST_ACTIONS } from '../protocol'
export {
  PAID_PRICES_USD,
  MODEL_API_PRICES_PER_MILLION,
  MODEL_API_PRICED_MODELS,
  PAID_DAILY_BUDGET,
  CODE_INTEL_TOOLS,
  IDE_CODE_INTEL_TOOLS,
  SCHEDULE_DEFAULT_INTERVAL_MS,
  DICTATION_KEY,
} from '../constants'
export {
  MSP_FRAME_LIMIT_BYTES,
  BUILTIN_AGENT_EXPLORE_ID,
  BUILTIN_AGENT_SECOND_OPINION_ID,
} from '../constants'
export {
  TEXT_ATTACHMENT_EXTENSIONS,
  MAX_MODEL_API_TEXT_ATTACHMENT_BYTES,
  MSP_ATTACHMENT_FRAME_BUDGET_BYTES,
  CONTEXT_PRESSURE_MEDIUM,
  CONTEXT_PRESSURE_HIGH,
  MILLISECONDS_PER_SECOND,
} from '../constants'

export {
  SCHEDULE_MIN_INTERVAL_MS,
  SCHEDULE_MAX_INTERVAL_MS,
  SCHEDULE_MAX_PROMPT_CHARS,
  SCHEDULE_MAX_JOBS_PER_SESSION,
  RESUME_SKILL_SELECTORS,
  EXPORT_FORMATS,
  EXEC_USD_DECIMALS,
  EXEC_UNTRUSTED_FILES_MAX,
  EXEC_UNTRUSTED_FILE_MAX_BYTES,
  EXEC_UNTRUSTED_TOTAL_MAX_BYTES,
  EXEC_PROMPT_MAX_BYTES,
  QUESTION_DEFER_DEFAULT_SECONDS,
  QUESTION_DEFER_MIN_SECONDS,
  QUESTION_DEFER_MAX_SECONDS,
} from '../constants'

export { MODEL_API_TOOLS, MODEL_API_SUBAGENT_TOOLS, VERIFY_TOOLS } from '../constants'
export const REFERENCE_TOOL_FEATURES: Readonly<Record<string, string>> = {
  read_file: 'attachments',
  write_file: 'chat',
  edit_file: 'edit-review',
  search: 'chat',
  list_files: 'chat',
  bash: 'shell',
  powershell: 'shell',
  ask_user: 'questions',
  todo_write: 'tasks',
  read_skill: 'skills',
  generate_image: 'images',
  edit_image: 'images',
  create_goal: 'goals',
  get_goal: 'goals',
  update_goal: 'goals',
  report_progress: 'goals',
  read_memory: 'memory',
  add_memory: 'memory',
  edit_memory: 'memory',
  recall_output: 'code-output',
  web_fetch: 'web-fetch',
  browser_check: 'browser',
  subagent_spawn: 'subagents',
  subagent_status: 'subagents',
  subagent_wait: 'subagents',
  subagent_send_message: 'subagents',
  subagent_read_result: 'subagents',
  subagent_cancel: 'subagents',
  run_checks: 'verify',
  verify_edits: 'verify',
}

export { LINUX_RECORDERS } from '../constants'

export { CLI_OPTION_REGISTRY, CLI_OPTION_TEXT } from '../../runtime/cliOptions'
export { SLASH_REFERENCE } from '../slashCommands'

export { PAID_USE_REGISTRY, isPaidSettingOn } from '../paid'

export { resolveSettingDefault, resolveCommandCondition } from './resolvers'

export { REFERENCE_POOL_RADIX } from '../constants'
